### ISSUE TITLE
Nammando Issues

### ISSUE THREAD

**Issue by FORCED-REASSEMBLY** [TeamMoonstorm/Starstorm2#10]
Gouge does not exist on any of his attacks, The camera does not return to normal after using the alternative special, Teleporter Effects are large, alt special does not have any VFX, Nemmando's sword and Gun disappear when the Invisible buff is applied.

**Comment by FORCED-REASSEMBLY** [comment]
Default Secondary sometimes decides not to exist

**Comment by FORCED-REASSEMBLY** [comment]
Update on the M2 issue. It seems to only happen when you have more than one stock and hold the ability in

**Comment by FORCED-REASSEMBLY** [comment]
here is the log @Nebby1999
[NemmandoIssues.txt](https://github.com/TeamMoonstorm/Starstorm2/files/8912528/NemmandoIssues.txt)

**Comment by FORCED-REASSEMBLY** [comment]
this should also include the Mastery Skin bug from another thread

**Comment by Nebby1999** [comment]
Fixed in the newest alpha release of SS2.

Link (Requires access to the SS2 discord server): https://discordapp.com/channels/753709254598328400/754484105584050216/993600660199198881

Note: Please create a separate issue with the M2 issue @FORCED-REASSEMBLY
