### ISSUE TITLE
X4 Balance - healing can be procced too quickly

### ISSUE THREAD

**Issue by gaforb** [TeamMoonstorm/Starstorm2#102]
Nemmando Single Tap is essentially free full healing at all times - And Mul-T Powermode and Railgunner are naturally broken due to their weird secondary interactions. I'd suggest only allowing the heal to apply if the skill has restocked since you last used it, effectively limiting it to the first shot of single-tap or whatever primary mul-t has

For railgunner, maybe a special case where it applies to the first shot while scoped instead of the actual scoping action, similar to how backup magazine has special behaviour.

**Comment by Zenithrium** [comment]
I initially planned on giving RG a special interaction but decided that spam scoping isn't really the best use of your time (but i'd be willing to give them a special interaction) 

I honestly didn't remember single tap and the mul-t thing existed, so yeah, that'd probably be fair. I kind of liked the fact that it synergized with backup mag though, in that having both allowed a nice burst of healing - maybe there's a workaround but I'm not sure.

**Comment by Zenithrium** [comment]
Actually, the lazy way would to code in a backup mag synergy specifically, adding +1 to the number of times it can proc before needing to wait for the stock to recharge. Would anyone be against that?

**Comment by gaforb** [comment]
I was going to suggest exactly that, plus allowing for X additional scoped shots with railgunner (X = backup mags) before it stops proccing

Executioner currently heals once whenever they fire a burst regardless of how many shots are fired which is perfect honestly, but not sure how you'd make backup mag interact there

**Comment by Zenithrium** [comment]
I might just make executioner excluded from the whole backup mag interaction. It's more weird hardcoded nonsense but I think it's probably fine. I think I'll probably keep the scope-in interaction for railgunner's alt secondary though, as I don't really know how else to make that one not busted. I don't even think backup mag works on that skill.

**Comment by leMalfaisant** [comment]
Unsure about the recharge stuff. Seems like it would make it not work on Classic Sniper. I’d probably just make it have a 0.5 to 1sec hidden cooldown.
