### ISSUE TITLE
Issue with animations, I think is may have to do with MSU as opposed to SS2 specifically

### ISSUE THREAD

**Issue by oceanselemon** [TeamMoonstorm/Starstorm2#106]
I first opened an issue a couple days ago for the same issue, only that time I closed it after manually figuring out that turning off Lost in Transit fixed it. Now it is back.
[log.txt](https://github.com/TeamMoonstorm/Starstorm2/files/9816021/log.txt)
As far as I can tell, it has something to do with unique cases of items leaving your inventory interfering with other cases of items leaving your inventory (Tinker's Satchel's Mimic, when it jumps on an item it makes a phantom clone for the +1, and when it leaves things go wonky). When this error pops up, suddenly animations stop ending. The easiest example I have seen of this is to play loader, and when you think things are wonky, try your secondary. If, upon returning to you, it simply sits stationary wherever you were, it has happened.
My modman profile code is TjhHiWVJDk.
The error I am talking about is posted below (not the whole thing, but the basics):

[Error  : Unity Log] KeyNotFoundException: The given key was not present in the dictionary.
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <44afb4564e9347cf99a1865351ea8f4a>:IL_001E)
Moonstorm.Starstorm2.BaseItemMasterBehavior.UpdateMasterItemBehaviorStacks (RoR2.CharacterMaster master) (at <f6c738a5cb5742c18440e6c6da91e67e>:IL_0010)
Moonstorm.Starstorm2.BaseItemMasterBehavior.CharacterMaster_OnInventoryChanged (On.RoR2.CharacterMaster+orig_OnInventoryChanged orig, RoR2.CharacterMaster self) (at <f6c738a5cb5742c18440e6c6da91e67e>:IL_0007)
DMD<>?-1755350784.Hook<RoR2.CharacterMaster::OnInventoryChanged>?-971826944 (RoR2.CharacterMaster ) (at <1abfbe3118d8424790c60112818000c4>:IL_000A)
RoR2.Inventory.HandleInventoryChanged () (at <abee4f3b46184662b4d0bd0bc9965114>:IL_000A)
DMD<RemoveItem>?-1755350784._RoR2_Inventory::RemoveItem (RoR2.Inventory this, RoR2.ItemIndex itemIndex, System.Int32 count) (at <5b7f750448b944b395bc9c2aaa977bd0>:IL_0076)
DMD<>?-1755350784.Trampoline<RoR2.Inventory::RemoveItem>?839226368 (RoR2.Inventory , RoR2.ItemIndex , System.Int32 ) (at <b8e6c38a41124ad2a9260a86833f035f>:IL_0020)
GOTCE.Items.NFT.Inventory_RemoveItem_ItemIndex_int (On.RoR2.Inventory+orig_RemoveItem_ItemIndex_int orig, RoR2.Inventory self, RoR2.ItemIndex itemIndex, System.Int32 count) (at <3197b90e2eee4a82827d2d5724f1a37d>:IL_0021)
DMD<>?-1755350784.Hook<RoR2.Inventory::RemoveItem>?781635968 (RoR2.Inventory , RoR2.ItemIndex , System.Int32 ) (at <1cc15bdff20342a78544502ac6f34c28>:IL_0014)
DMD<>?-1755350784.Trampoline<RoR2.Inventory::RemoveItem>?681307136 (RoR2.Inventory , RoR2.ItemIndex , System.Int32 ) (at <72a196f2ab184dbc99f4a2161ef47e4b>:IL_0020)
ThinkInvisible.TinkersSatchel.Mimic.On_InvRemoveItemByIndex (On.RoR2.Inventory+orig_RemoveItem_ItemIndex_int orig, RoR2.Inventory self, RoR2.ItemIndex itemIndex, System.Int32 count) (at <1a0b17a8b2154fa0afef8e82b7f9298d>:IL_0001)
DMD<>?-1755350784.Hook<RoR2.Inventory::RemoveItem>?-1836860160 (RoR2.Inventory , RoR2.ItemIndex , System.Int32 ) (at <826c61af9a634547bb6adcdcb7a41408>:IL_0014)
DMD<>?-1755350784.Trampoline<RoR2.Inventory::RemoveItem>?2127534080 (RoR2.Inventory , RoR2.ItemIndex , System.Int32 ) (at <9a164fa6061641378babbef3210f200b>:IL_0020)

**Comment by Nebby1999** [comment]
i can confirm that this is not MSU Related, as "BaseItemMasterBehaviour" is a class in SS2.

**Comment by oceanselemon** [comment]
Right, this problem is gone, now something else is wrong. Closing, will make a new issue notice.
