### ISSUE TITLE
[not sure if its a real issue] inferno difficulty appears before typhoon despite inferno being more difficult than typhoon

### ISSUE THREAD

**Issue by Mick0604** [TeamMoonstorm/Starstorm2#107]
Not sure of this counts but it just looks odd to have typhoon be last if inferno is harder

**Comment by Nebby1999** [comment]
Difficulty is subjective, literally.

Internally Difficulties have a Scaling Value which determines how "difficult" the run is going to be, The game sorts the difficulties in the game by the scaling values, it just so happens that Inferno's DifficultyDef by default is 3, the same as Monsoon, Typhoon is 3.5, Typhoon is greater so it shows after inferno.
