### ISSUE TITLE
Comically large Ancient Scepter

### ISSUE THREAD

**Issue by bruhster2548** [TeamMoonstorm/Starstorm2#110]
![image](https://user-images.githubusercontent.com/97296442/196925050-7476ada2-4249-4252-88fe-e61a08c1895b.png)
[zipped_log.zip](https://github.com/TeamMoonstorm/Starstorm2/files/9828866/zipped_log.zip)

**Comment by leMalfaisant** [comment]
Issue with Ancient Scepter, will unfortunately have to wait for an update on that.
