### ISSUE TITLE
Greater Warbanner Spam

### ISSUE THREAD

**Issue by nickshieldsart** [TeamMoonstorm/Starstorm2#119]
There's a glitch with the greater warbanner where it will sometimes start spawning itself infinitely at the start of a stage. 
Log file attached
Profile code: 7vJxabXSPl

**Comment by nickshieldsart** [comment]
[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/9848025/LogOutput.log)

**Comment by Redund0** [comment]
I also had a greater warbanner spam issue. Gave it to equipment drone stage 5, everything was fine.
Went to moon, everything was fine at first, but after activating first pillar he obliterated my game with warbanner drops.
[zipped_log.zip](https://github.com/TeamMoonstorm/Starstorm2/files/10094320/zipped_log.zip)
