### ISSUE TITLE
Portable Reactor 

### ISSUE THREAD

**Issue by FORCED-REASSEMBLY** [TeamMoonstorm/Starstorm2#12]
![unknown](https://user-images.githubusercontent.com/99555702/174439967-871c6072-10e8-4366-9710-35f6bae7126e.png)
Portable reactor causes the player to become magenta for the time that you're invincible
[PortableReactor.txt](https://github.com/TeamMoonstorm/Starstorm2/files/8933615/PortableReactor.txt)

**Comment by Phreelosu** [comment]
exact same issue with Hunter's Sigil, the buff is supposed to be shown on your character which makes it purple
since the textures arent loading properly, Hunter's Sigil's buff suffers the same fate

**Comment by Nebby1999** [comment]
Fixed in the newest alpha release of SS2.

Link (Requires access to the SS2 discord server): https://discordapp.com/channels/753709254598328400/754484105584050216/993600660199198881
