### ISSUE TITLE
Multiplayer doesn't properly integrate non-hosts into the game

### ISSUE THREAD

**Issue by TheOutlier876** [TeamMoonstorm/Starstorm2#120]
When playing multiplayer, the host can play fine, like nothing's wrong, however my friends either don't spawn in properly, with the camera stuck under the map, and their healthbar not fully showing up, or they don't spawn at all and just stay in the character select. They still receive all chat messages and screen effects like they're dropping from the pod, but never actual spawn. Have tried going thru the portal while player is stuck in character select but it doesn't spawn them next stage, have not tried stage spawning for when they get spawned in wrong.

**Comment by Zenithrium** [comment]
log? this sounds like an issue that happens when like 100 mods are installed

**Comment by TheOutlier876** [comment]
I thought the same thing, so I tried it with just starstorm and tested stuff with just startstorm + dependencies

**Comment by Zenithrium** [comment]
and the same thing happened? could still be a pc issue... also, uh, log please?

**Comment by TheOutlier876** [comment]
nah, I have a better PC so I tried swapping roles, my friend could play fine as host while I got stuck in menu. Also, I'm new to GitHub, do you just mean the BepInX log? Sorry

**Comment by Zenithrium** [comment]
yea the bepinex log

**Comment by TheOutlier876** [comment]
I already closed all of it, sorry. we'll be trying more stuff tmrw to try and get it work, so I'll try and update then. Thanks so far tho, sorry for the lack of information

**Comment by TheOutlier876** [comment]
Alright I figured it out. I still had Tiler2 activated and I think the multiplayer configs were clashing. It fixed it immediately.

**Comment by TheOutlier876** [comment]
[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/9884972/LogOutput.log)
idk if you still want it but here's the log I guess
