### ISSUE TITLE
Weird Black Squares/VFX on Executioner

### ISSUE THREAD

**Issue by ColdMartini** [TeamMoonstorm/Starstorm2#125]
https://user-images.githubusercontent.com/116767057/198149178-23b01ef9-d41d-41ed-b1b7-78a0937df0db.mp4

**Comment by Zenithrium** [comment]
huh it's back

**Comment by leMalfaisant** [comment]
this was caused by some sort of hardware issue last time, specs?

**Comment by ColdMartini** [comment]
Gpu is a Nvidia 2070 Max Q (Ew nasty)

**Comment by ColdMartini** [comment]
Any news on the bug?

**Comment by Zenithrium** [comment]
i think you just need to update your drivers yeah

**Comment by ColdMartini** [comment]
Cool, thanks! I usually don't update 'em cuz it tends to cause more
problems but it seems it's about that time to update.

**Comment by leMalfaisant** [comment]
closing this then, issue resolved
