### ISSUE TITLE
Nkuna's Heritage is hilariously faulty

### ISSUE THREAD

**Issue by RhapsodySL** [TeamMoonstorm/Starstorm2#126]
This might be because of a weird mod interaction but sometime after picking Nkuna's Heritage, my level would start to go _down_ briefly and go back up sometimes. At first this would result in just an item or so gained when I didn't _actually_ level up, but it would give me an items for each level "gained" this way. After a while in the Void Fields I would start spewing out items to the point where my game crashed after a few more waves. [Video](https://youtu.be/PFuY_PZ7Igg?t=30). It got a lot worse past this point but Gamebar wasn't having it and wouldn't save the recording.

Here's my full modlist:

https://rhap.city/i/j8zJw.png
https://rhap.city/i/3igM5.png

Here's the profile code if you need it for testing: QIoZuNbqZ6 
Here's the log file: https://www.dropbox.com/s/rx1r6fztc1ljdhs/LogOutput.log?dl=0

I should probably mention that the log file is like 350MB, probably because of this issue. Have fun with that.

**Comment by Zenithrium** [comment]
should be fixed, hopefully
