### ISSUE TITLE
Dedicated server crashes on launch with SS2

### ISSUE THREAD

**Issue by 18tygerw** [TeamMoonstorm/Starstorm2#128]
Been trying to get my dedicated server working with SS2 lately! The server is being run through r2modman, and I've tried installing it manually as well, but nothing has worked so far. My current testing profile is using BepInExPack, HookGenPatcher, R2API, MoonstormSharedUtils, and Starstorm2.

Always ends in a Unity crash, not sure why.

Profile code: 16GB7ol6rv

[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/9875856/LogOutput.log)

**Comment by 18tygerw** [comment]
I'd like to add that the server works when MSU is installed, but not SS2. LostInTransit doesn't seem to cause the crash when added either.
Maybe something in SS2 is causing the Unity crash?

**Comment by 18tygerw** [comment]
![image](https://user-images.githubusercontent.com/72367133/198419250-55fc77f6-e36f-4502-8cc4-3370c584837e.png)
The BepInExGUI log seems to be showing less info than the crash report, here ya go.
[error.log](https://github.com/TeamMoonstorm/Starstorm2/files/9883755/error.log)

**Comment by prodzpod** [comment]
it seems like it was trying to do file I/O then failed. further testing is needed

**Comment by xiaoxiao921** [comment]
This is because Starstorm (and a lot of other mods) are trying to access Wwise functions even though the sound engine is not initialized in dedicated server, I fixed this for all mods through the https://github.com/risk-of-thunder/RoR2BepInExPack project, you can close this

**Comment by Nebby1999** [comment]
That's very much what I was going to say, I'm closing this down now

**Comment by 18tygerw** [comment]
Thank you for all your hard work!
