### ISSUE TITLE
Molten Coin triggering NRE spam in console

### ISSUE THREAD

**Issue by TrueMemeKing** [TeamMoonstorm/Starstorm2#129]
[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/9875923/LogOutput.log)
Molten Coin seems to be missing its sound effect, and after it tries to play the sound a large NRE appears in the log

**Comment by Zenithrium** [comment]
couldn't replicate this - please do tell if it continues to happen in the current build

**Comment by TrueMemeKing** [comment]
Tried a run with just Starstorm/MoonstormUtils installed on a fresh profile, error did not appear during the run, but _did_ appear as the run ended.
 [Error  : Unity Log] KeyNotFoundException: The given key was not present in the dictionary.
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <44afb4564e9347cf99a1865351ea8f4a>:IL_001E)
Moonstorm.Starstorm2.BaseItemMasterBehavior.UpdateMasterItemBehaviorStacks (RoR2.CharacterMaster master) (at <fd6eb3b9f28048e08774a64128a49926>:IL_0010)
Moonstorm.Starstorm2.BaseItemMasterBehavior.CharacterMaster_OnInventoryChanged (On.RoR2.CharacterMaster+orig_OnInventoryChanged orig, RoR2.CharacterMaster self) (at <fd6eb3b9f28048e08774a64128a49926>:IL_0007)
DMD<>?-829299456.Hook<RoR2.CharacterMaster::OnInventoryChanged>?1635285632 (RoR2.CharacterMaster ) (at <0e55c849ac994cd79957fb1fd9ee4377>:IL_000A)
RoR2.Inventory.HandleInventoryChanged () (at <abee4f3b46184662b4d0bd0bc9965114>:IL_000A)
RoR2.Inventory.RemoveItem (RoR2.ItemIndex itemIndex, System.Int32 count) (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0076)
RoR2.MinionOwnership+MinionGroup.RemoveMinion (UnityEngine.Networking.NetworkInstanceId ownerId, RoR2.MinionOwnership minion) (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0015)
RoR2.MinionOwnership+MinionGroup.SetMinionOwner (RoR2.MinionOwnership minion, UnityEngine.Networking.NetworkInstanceId ownerId) (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0022)
RoR2.MinionOwnership.OnDestroy () (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0000)

Seems like a MoonstormUtil issue that relates to the despawning of characters, but becomes significantly more present in my profile with a lot of other mods when compared to just on it's own. Having lots of minions, via happiest mask or a modded item such as Wildlife Camera causes lots of NREs from when they despawn and tanks framerate. Without lots of summons usually only appears during a transition to the next stage or despawning the player as the run ends.

**Comment by prodzpod** [comment]
please test this on the newest version of MSU.

**Comment by TrueMemeKing** [comment]
[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/11155406/LogOutput.log)
Tested, issue still exists. KeyNotFound exceptions still can appear, definitely seems to linked to minions in some way, as my equipped items had Droid Head which was generating drones. Molten Coin still also doesn't make a sound, but this doesn't seem to be the root cause of the issue.

**Comment by prodzpod** [comment]
@Nebby1999 yo msu issue?

**Comment by Nebby1999** [comment]
where exactly cuz there's a lot of things in the log x-x

> @Nebby1999 yo msu issue?

**Comment by TrueMemeKing** [comment]
Down near the bottom of the log, before the player death there's one of the KeyNotFound blocks;
[Error  : Unity Log] KeyNotFoundException: The given key was not present in the dictionary.
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <44afb4564e9347cf99a1865351ea8f4a>:IL_001E)
Moonstorm.Starstorm2.BaseItemMasterBehavior.UpdateMasterItemBehaviorStacks (RoR2.CharacterMaster master) (at <c03f96aaf547448db4bb8a15e2af2198>:IL_0010)
Moonstorm.Starstorm2.BaseItemMasterBehavior.CharacterMaster_OnInventoryChanged (On.RoR2.CharacterMaster+orig_OnInventoryChanged orig, RoR2.CharacterMaster self) (at <c03f96aaf547448db4bb8a15e2af2198>:IL_0007)
DMD<>?1723531264.Hook<RoR2.CharacterMaster::OnInventoryChanged>?-47998720 (RoR2.CharacterMaster ) (at <541212349e9d44de830583eb613d38c6>:IL_000A)
DMD<>?1723531264.Trampoline<RoR2.CharacterMaster::OnInventoryChanged>?420969472 (RoR2.CharacterMaster ) (at <686a7994b12444099b2266d861c53191>:IL_0020)
GanondorfMod.Modules.Achievements.EightLunarItemsAchievement.CheckItem (On.RoR2.CharacterMaster+orig_OnInventoryChanged orig, RoR2.CharacterMaster self) (at <fdce674adecd414889822e11e55837f2>:IL_0001)
DMD<>?1723531264.Hook<RoR2.CharacterMaster::OnInventoryChanged>?968669184 (RoR2.CharacterMaster ) (at <ca6911cce7af47d2900e53b59f81d3c7>:IL_0014)
DMD<>?1723531264.Trampoline<RoR2.CharacterMaster::OnInventoryChanged>?-215802880 (RoR2.CharacterMaster ) (at <d49fab18842343f0b61336e98fe95c5c>:IL_0020)
GanondorfMod.Modules.Achievements.ItemExperiementationAchievement.CheckItem (On.RoR2.CharacterMaster+orig_OnInventoryChanged orig, RoR2.CharacterMaster self) (at <fdce674adecd414889822e11e55837f2>:IL_0001)
DMD<>?1723531264.Hook<RoR2.CharacterMaster::OnInventoryChanged>?-1074306816 (RoR2.CharacterMaster ) (at <6000ceb83d9c4693a1498fc4ff68cb61>:IL_0014)
RoR2.Inventory.HandleInventoryChanged () (at <abee4f3b46184662b4d0bd0bc9965114>:IL_000A)
DMD<RemoveItem>?1723531264._RoR2_Inventory::RemoveItem (RoR2.Inventory this, RoR2.ItemIndex itemIndex, System.Int32 count) (at <85bf10bc60554e3abc511fb3376c3383>:IL_0076)
DMD<>?1723531264.Trampoline<RoR2.Inventory::RemoveItem>?-1913846784 (RoR2.Inventory , RoR2.ItemIndex , System.Int32 ) (at <4b11fabfc40549f6800be54d70bae271>:IL_0020)
MysticsItems.Items.Manuscript.Inventory_RemoveItem_ItemIndex_int (On.RoR2.Inventory+orig_RemoveItem_ItemIndex_int orig, RoR2.Inventory self, RoR2.ItemIndex itemIndex, System.Int32 count) (at <6cc8599695004ece8e90ebbcf145deea>:IL_0021)
DMD<>?1723531264.Hook<RoR2.Inventory::RemoveItem>?470007040 (RoR2.Inventory , RoR2.ItemIndex , System.Int32 ) (at <276cbe21c1ca4bdf90c445202907daa5>:IL_0014)
RoR2.MinionOwnership+MinionGroup.RemoveMinion (UnityEngine.Networking.NetworkInstanceId ownerId, RoR2.MinionOwnership minion) (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0015)
RoR2.MinionOwnership+MinionGroup.SetMinionOwner (RoR2.MinionOwnership minion, UnityEngine.Networking.NetworkInstanceId ownerId) (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0022)
RoR2.MinionOwnership.OnDestroy () (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0000)

[Warning:Moonstorm Shared Utils] Could not find sound event with name of MoltenCoin
[Warning:Moonstorm Shared Utils] Could not find sound event with name of MoltenCoin

**Comment by Nebby1999** [comment]
> Down near the bottom of the log, before the player death there's one of the KeyNotFound blocks; [Error : Unity Log] KeyNotFoundException: The given key was not present in the dictionary. Stack trace: System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <44afb4564e9347cf99a1865351ea8f4a>:IL_001E) Moonstorm.Starstorm2.BaseItemMasterBehavior.UpdateMasterItemBehaviorStacks (RoR2.CharacterMaster master) (at :IL_0010) Moonstorm.Starstorm2.BaseItemMasterBehavior.CharacterMaster_OnInventoryChanged (On.RoR2.CharacterMaster+orig_OnInventoryChanged orig, RoR2.CharacterMaster self) (at :IL_0007) DMD<>?1723531264.HookRoR2.CharacterMaster::OnInventoryChanged?-47998720 (RoR2.CharacterMaster ) (at <541212349e9d44de830583eb613d38c6>:IL_000A) DMD<>?1723531264.TrampolineRoR2.CharacterMaster::OnInventoryChanged?420969472 (RoR2.CharacterMaster ) (at <686a7994b12444099b2266d861c53191>:IL_0020) GanondorfMod.Modules.Achievements.EightLunarItemsAchievement.CheckItem (On.RoR2.CharacterMaster+orig_OnInventoryChanged orig, RoR2.CharacterMaster self) (at :IL_0001) DMD<>?1723531264.HookRoR2.CharacterMaster::OnInventoryChanged?968669184 (RoR2.CharacterMaster ) (at :IL_0014) DMD<>?1723531264.TrampolineRoR2.CharacterMaster::OnInventoryChanged?-215802880 (RoR2.CharacterMaster ) (at :IL_0020) GanondorfMod.Modules.Achievements.ItemExperiementationAchievement.CheckItem (On.RoR2.CharacterMaster+orig_OnInventoryChanged orig, RoR2.CharacterMaster self) (at :IL_0001) DMD<>?1723531264.HookRoR2.CharacterMaster::OnInventoryChanged?-1074306816 (RoR2.CharacterMaster ) (at <6000ceb83d9c4693a1498fc4ff68cb61>:IL_0014) RoR2.Inventory.HandleInventoryChanged () (at :IL_000A) DMD?1723531264._RoR2_Inventory::RemoveItem (RoR2.Inventory this, RoR2.ItemIndex itemIndex, System.Int32 count) (at <85bf10bc60554e3abc511fb3376c3383>:IL_0076) DMD<>?1723531264.TrampolineRoR2.Inventory::RemoveItem?-1913846784 (RoR2.Inventory , RoR2.ItemIndex , System.Int32 ) (at <4b11fabfc40549f6800be54d70bae271>:IL_0020) MysticsItems.Items.Manuscript.Inventory_RemoveItem_ItemIndex_int (On.RoR2.Inventory+orig_RemoveItem_ItemIndex_int orig, RoR2.Inventory self, RoR2.ItemIndex itemIndex, System.Int32 count) (at <6cc8599695004ece8e90ebbcf145deea>:IL_0021) DMD<>?1723531264.HookRoR2.Inventory::RemoveItem?470007040 (RoR2.Inventory , RoR2.ItemIndex , System.Int32 ) (at <276cbe21c1ca4bdf90c445202907daa5>:IL_0014) RoR2.MinionOwnership+MinionGroup.RemoveMinion (UnityEngine.Networking.NetworkInstanceId ownerId, RoR2.MinionOwnership minion) (at :IL_0015) RoR2.MinionOwnership+MinionGroup.SetMinionOwner (RoR2.MinionOwnership minion, UnityEngine.Networking.NetworkInstanceId ownerId) (at :IL_0022) RoR2.MinionOwnership.OnDestroy () (at :IL_0000)
> 
> [Warning:Moonstorm Shared Utils] Could not find sound event with name of MoltenCoin [Warning:Moonstorm Shared Utils] Could not find sound event with name of MoltenCoin

These specifically relating to the "BaseItemMasterBehaviour" are not related to MSU, this is due to the namespace of the behaviour being inside the "Moonstorm.**Starstorm**" namespace.

outside of this, the warning regarding the SoundEvent with name MoltenCoin is due to the NetworkedSoundEvent not existing, iether it was removed or the name changed. the method all it does is get the NetworkedSFX from the catalog using the name and plays it.
