### ISSUE TITLE
random? instant death 

### ISSUE THREAD

**Issue by breadguy69** [TeamMoonstorm/Starstorm2#131]
https://user-images.githubusercontent.com/21149431/198421433-1fbac0d2-08df-47a2-bcd5-41e5e227b75f.mp4

[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/9883812/LogOutput.log)

last thing in log before death was an ss2 nre i think

**Comment by Zenithrium** [comment]
this was HolyDLL right?

**Comment by breadguy69** [comment]
yeah, I think it got solved on discord and I forgor to close the issue

**Comment by swuff-star** [comment]
hi breadguy
