### ISSUE TITLE
Strange bug items appears to not being picked up meanwhile able to pick up infinitely 

### ISSUE THREAD

**Issue by Matyeeeee** [TeamMoonstorm/Starstorm2#133]
![image](https://user-images.githubusercontent.com/116907143/198695424-ee27c2f6-ea39-4c9b-bc99-2e2ee02c06da.png)
![image](https://user-images.githubusercontent.com/116907143/198695480-f474367a-68fc-4325-be86-ae2c9cfa3d99.png)
![image](https://user-images.githubusercontent.com/116907143/198695501-741877c1-d0a1-420d-a5d9-1bb2f3958a9b.png)

[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/9890594/LogOutput.log)

**Comment by Slipskip** [comment]
Probably related to running an older version of risk of rain 2 if this error in your log is anything to go by
[Warning:     R2API] This version of R2API was built for build id "1.2.4.1", you are running "1.2.2.0".

**Comment by Zenithrium** [comment]
it could easily be an IDRs issue - ill check if either of those items have wrong displays

**Comment by Matyeeeee** [comment]
I updated to 1.2.4.1 Build quick tested it and it works! Ty
