### ISSUE TITLE
Executioner ion burst not working on high attack speeds

### ISSUE THREAD

**Issue by DanKerslager** [TeamMoonstorm/Starstorm2#134]
When on high attack speeds (around 6+)  ion burst does not use or fire any shots. The skill gets used, because I get healing from X-4 stimulant (every tick it seems), this part might be connected with me using deadly voltage, without it, the skill just doesn't fire.
I think it has to do with me shooting ion burst so fast, game cant process it. Using deadly voltage resets the skill activation, resulting in healing.
Attack speed was achieved with 2 zenith accelerators (and some syringes) so when attack speed dropped, ion burst worked ok.

**Comment by prodzpod** [comment]
executioner will be reworked in the foreseeable future, please report again when the issue persists after the rework
