### ISSUE TITLE
executioner becoming grossly incandescent still?

### ISSUE THREAD

**Issue by SarahTonin69** [TeamMoonstorm/Starstorm2#137]
[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/9894523/LogOutput.log)
yea i'm gonna be honest this is a strange one, i picked up x-4 stimulant and then i became the sun again, i was using the wastelander skin but as soon as i hit the blouth and went to the newt shop it turned me into the default skin??? but i was still super bright. very strange, hopefully i didn't report this incorrectly im not very smart so please tell me if i reported bug wrong

**Comment by SarahTonin69** [comment]
ALSO when i went to the next stage, my skin changed back???????

**Comment by Zenithrium** [comment]
i wasnt confident i fixed it so i might just try with a different method later

**Comment by SarahTonin69** [comment]
i also just tried dropping x-4 stimulant, and then respawning, my skin changed again but im not glowing anymore
hopefully this info helps??? sorry if not :(
