### ISSUE TITLE
Typhoon still selectable with SS2 expansion disabled

### ISSUE THREAD

**Issue by Slipskip** [TeamMoonstorm/Starstorm2#140]
This ones minor as hell but also pretty self explanatory. Typhoon also works just fine in game with the expansion disabled.
No log cause there's no errors or anything in there.
![20221029220506_1](https://user-images.githubusercontent.com/104352318/198852362-b347bd30-c9c2-4072-9aed-5811bea5d7ef.jpg)

**Comment by Zenithrium** [comment]
unless i'm blind (which is possible & likely) it doesn't seem like it's possible to define a difficulty under an expansion. there's probably a workaround though

**Comment by Zenithrium** [comment]
i don't think there's anything that can be done about this, so i'm closing it
