### ISSUE TITLE
X-4 Stimulant on Executioner

### ISSUE THREAD

**Issue by kellio23** [TeamMoonstorm/Starstorm2#141]
Picking up the X-4 Stimulant while playing executioner creates a massive amount of light coming from the player model making it so you cant see anything, others in multiplayer also get blinded. It also sets the M2 cooldown much lower than what the item says it would. Scrapping the item, dying and reviving stops the effect but it stays on the body. Changing stages does not stop the effect. This happened of both the default and second skin for executioner
![steamwebhelper_iupTCOjq4V](https://user-images.githubusercontent.com/56138610/198853249-7b061ac5-df57-483b-88be-9927f06f17fc.jpg)
![steamwebhelper_8mLjlYNnzi](https://user-images.githubusercontent.com/56138610/198853255-3868adc9-858e-4f79-92d4-b0f95652690d.png)
![steamwebhelper_5rnxoB1wVm](https://user-images.githubusercontent.com/56138610/198853257-8ba684dc-404c-467f-a6d9-52a657146c99.jpg)

**Comment by Zenithrium** [comment]
just like, whenever you use it with exe? or did you do something in particular to make this happen. i just fixed the cooldown code on x4 and it's not happening - am i right to assume it was that?

**Comment by Zenithrium** [comment]
Fixed in 0.3.45!
