### ISSUE TITLE
relic of force + malice exponential damage bug

### ISSUE THREAD

**Issue by gregeresterest** [TeamMoonstorm/Starstorm2#146]
if you have at least 2 relic of force and 1 malice, relic of force can be triggered and can also trigger malice without anything stopping it from doing this over and over again causing exponential damage, i think this happens by 

malice hitting an enemy
2+ instances of extra damage are triggered causing an equal amount of malice to hit the other enemy again
each instance of malice cause another 2+ instanced of force damage causing infinite damage scaling

**Comment by Zenithrium** [comment]
Fixed in 0.3.45!
