### ISSUE TITLE
Change colors to black and white.

### ISSUE THREAD

**Issue by Nuychibay** [TeamMoonstorm/Starstorm2#149]
I ran into a problem when I picked up an item on the X-4 Stimulant executioner, and pressed the 3rd skill, all the colors were replaced with black and white.
Sorry for bad English.
I am attaching a screenshot.
![unknown](https://user-images.githubusercontent.com/117093420/199024547-558c85e3-0d50-4ea1-81ec-82ae42aa60ec.png)

**Comment by Zenithrium** [comment]
i think this got fixed? feel free to reopen it if it's still happening
