### ISSUE TITLE
Certain mod character typhoon skins are not unlocking

### ISSUE THREAD

**Issue by muko7e2** [TeamMoonstorm/Starstorm2#150]
Me and my friend have beat Typhoon several times with the character named MEL-T, however the Grand-Mastery skin isn't unlocking, but the monsoon skin does unlock.
I do not know if this is a bug to your mod or to this particular character, so i am asking here first to see if i get a response.

This is the character in question:
https://thunderstore.io/package/PlasmaCore3/MELT/

Thank you.

**Comment by leMalfaisant** [comment]
Closing this issue, as it is an issue with MEL-T. Thanks for the report anyway, helps a lot.
