### ISSUE TITLE
Trying to get the Metamorphosis artifact in Bulwark's Ambry doesn't seem to work.

### ISSUE THREAD

**Issue by shiniebub** [TeamMoonstorm/Starstorm2#151]
I'm sure it's a Starstorm issue, I've used the same set of mods for the past few months (whilst achievement hunting), but ever since the update, I can't enter Bulwark's Ambry to get Metamorphosis. You load in to the level, the camera pans around the caged artifact, and instead of drifting the camera back to the player, it's just stuck on the artifact. I'd be happy to see if there are other people who've had this issue.

**Comment by prodzpod** [comment]
reproduced, wack bug, expect to be fixed in april release

**Comment by Nebby1999** [comment]
Issue itself is inside the ror2 code, a beepinexpack update should fix it
for now, we've decided to remove the expansion requirement on our survivors, itss a bandaid fix but it works for now.
