### ISSUE TITLE
Relic of Force is giving primary skills cooldowns

### ISSUE THREAD

**Issue by DarkPillWarrior** [TeamMoonstorm/Starstorm2#152]
I first noticed this the first time I grabbed the Relic of Force. I was using double tap, on the Commando, and it gave double tap a 0.5 second cooldown. I was doing a run today and it also gave the modded m1 for the Commando a 0.5 second cooldown. I have a picture of the modded m1 this time and also a picture showing the cooldown on the m1 after I use it. I just wanted to say something since I don't think it is supposed to give primary skills cooldowns.

![image](https://user-images.githubusercontent.com/117225501/199335567-22e35270-4d21-4938-bfed-971b88eaad82.png)
![image](https://user-images.githubusercontent.com/117225501/199335724-df16cf11-ff69-45fa-821f-0494f8f4d21b.png)

**Comment by prodzpod** [comment]
please list the skill mods you were using alongside it, could not repro with my profile

**Comment by Zenithrium** [comment]
think this was the same issue as the #175 / a similar one. The hook was being applied in the wrong place, and I think that gave skills cooldowns that shouldn't have them? I'd need to look in to it a bit more, but it might be fixed in my branch
