### ISSUE TITLE
Frames slowly drop to Zero

### ISSUE THREAD

**Issue by RuneAether** [TeamMoonstorm/Starstorm2#155]
Don't have video and don't know how to replicate it but when I was in Abandoned Aqueduct, I triggered some kind of event, it was Ancient something I believe, and then the game slowly started dropping frames until the game went from frames per second to seconds per frame. I managed to hit the teleporter and move on to the next stage where the lag stopped, so whatever it was was specifically an issue with that event/stage. Worth noting is that the text for the event didn't disappear until I left the stage.

**Comment by Nebby1999** [comment]
caused by MSU 1.1.1, update to 1.1.2 and it should be fixed
