### ISSUE TITLE
TypeLoadException spam during some storms

### ISSUE THREAD

**Issue by EtiTheSpirit** [TeamMoonstorm/Starstorm2#157]
This error needs to be tested a bit more to isolate the cause, which is incredibly unclear right now. I have chosen to report it anyway just for the sake of book-keeping since it seems to be related to storms, which are not controllable by the player anyway(?)

A storm started (I do not remember the exact type, I think cloudy or blizzard) while I was on The Moon. While the storm was active, an error was raised every frame.

```
[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000250 (from typeref, class/assembly Moonstorm.Starstorm2.Components.WindZoneController, MoonstormSharedUtils, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
Stack trace:
```

There is no stack trace attached to this message. As far as I am aware, no exact reproduction is possible as it is out of player control. When the storm stopped, the error stopped shortly afterwards as well.

Unfortunately, I only noticed this when checking the log after a strange periodic freeze started occurring. I don't know if the game freezing is related to this issue, but I speculate it is *not*, because a second storm happened shortly after and there was no freezing even though the error was occurring.

**Important Details:**
* I am not running the mod alone, but the nature of this error leads me to believe that other mods would not be able to interfere in the first place.
* The point of interest in the log file is Line 12818 of part 1 (this is a NRE prior to the error spam occurring). Unfortunately the log file was too big to attach in full, and I had to split it in half manually.
* The mod was downloaded via the Thunderstore Mod Manager and no manual installation steps were taken.

**Log files:**
* [Log_Part1.log](https://github.com/TeamMoonstorm/Starstorm2/files/9953152/Log_Part1.log)
* [Log_Part2.log](https://github.com/TeamMoonstorm/Starstorm2/files/9953153/Log_Part2.log)

Hopefully this provides at least some significant information about the issue.

**Comment by EtiTheSpirit** [comment]
I just wanted to post an update that I have done more testing and I don't know what kind of storm it is, but the label is "A storm is approaching..." and applies a buff where the icon is gray clouds. This is what I meant when I said "cloudy" in OP.

Once again I am getting the severe frame drops every few seconds, so it may be related to the storm after all.

**Comment by prodzpod** [comment]
seems to have been fixed with WindZoneController moving to MSU.
