### ISSUE TITLE
When I play as the executioner, some sprites become black squares

### ISSUE THREAD

**Issue by VilorTrees** [TeamMoonstorm/Starstorm2#159]
![Risk_of_Rain_2_bwIqovOcjq](https://user-images.githubusercontent.com/117739355/200572583-aed37cf8-c648-451a-a9fc-8e7603c67988.jpg)
![Risk_of_Rain_2_O0RcJ6BDEK](https://user-images.githubusercontent.com/117739355/200572607-6a44efba-4892-4e62-bf07-fa04bd3dad1e.jpg)
![Risk_of_Rain_2_tExhIx6284](https://user-images.githubusercontent.com/117739355/200572608-5fa73d3b-dcff-4550-94e8-3f7bb534bedc.jpg)
![Risk_of_Rain_2_wmRXSDiUm6](https://user-images.githubusercontent.com/117739355/200572614-30ada82a-bfa2-4138-a9f2-ce85de8cee17.jpg)
![Risk_of_Rain_2_X9dWjMkkon](https://user-images.githubusercontent.com/117739355/200572619-0c5615e0-b4e3-4949-9a59-728b7d45d17e.png)
![Risk_of_Rain_2_XiHEqRRuxf](https://user-images.githubusercontent.com/117739355/200572655-458fcbb5-85b1-43e7-bc67-744588bae65e.jpg)

**Comment by leMalfaisant** [comment]
Last time this was due to outdated drivers, could you check your drivers?

**Comment by VilorTrees** [comment]
Thanks. and really there was a problem in the drivers
