### ISSUE TITLE
starstorm seems to nullify changes made with "SurvivorEnemyAndSkillCustomizer"

### ISSUE THREAD

**Issue by AshuraVelles** [TeamMoonstorm/Starstorm2#160]
I tend to use the mod i mentioned to add/change some stats that each survivor has, but it brings an issue with startstorm, where the game loads and functions with star storm, but it completely removes any stat changes made with the previous mod , rending it basically worthless D:

**Comment by prodzpod** [comment]
please link me to the mod you are using

**Comment by Nebby1999** [comment]
Closing this as it's stale, reopen if needed
