### ISSUE TITLE
Ancient Scepter doesn't scale down to Nemcommando's size, and is instead giant.

### ISSUE THREAD

**Issue by EyelessJack69** [TeamMoonstorm/Starstorm2#162]
It's only a visual bug but still can be quite annoying for multiplayer, and even for singleplayer personally. Not to mention the scale and "layer: -1" errors the console is pumping out which may or may not be related. Is this all intentional? I hope not :(

**Comment by Zenithrium** [comment]
nothing we can do without the scepter mod updating or finishing the nemmando rework. at this rate, i think the latter is more likely
