### ISSUE TITLE
Field Accelerator not stacking correctly/at all

### ISSUE THREAD

**Issue by SpoonPotato** [TeamMoonstorm/Starstorm2#163]
Field accelerator does not seem to function correctly past the first stack, in the sense that the item does not stack at all. Found this issue on a long command run, before testing it out by spawning in stacks of it, up to 100. The first stack works as intended, but additional stacks do nothing.

**Comment by Nebby1999** [comment]
Field accelerator has incredibly harsh diminishing returns, it's hyperbolic scaling makes it so charge per kill will never be over 5% per kill.

I may look into the calculation to ensure it works properly

**Comment by SpoonPotato** [comment]
I see, I guess I should've tested this more, stacking further results in the percentage number skipping past %s. I do think that the item should have noticeable stacking effects without needing hundreds of stacks, but that's a balance issue, not a bug. Probably no need to look into the calculation.

**Comment by Darkmega18** [comment]
oh. really? well thats annoying. I thought each one was literally 1% more for a kill inside. but... 1% more of a 1%? :V I got 5 and it goes up by maybe 1 and a half% that feels kinda sad. :<
