### ISSUE TITLE
Items seem to be missing

### ISSUE THREAD

**Issue by B0wlingKing** [TeamMoonstorm/Starstorm2#165]
I can't find anywhere to check, since the wiki linked in the thunderstore is for Risk of Rain 1, but I think I'm missing items from this modpack such as dormant fungus. Is this normal, or am i just unable to find a list of the items?

**Comment by swuff-star** [comment]
There's a few currently disabled items, including Dormant Fungus. A list of the mod's items can be found on the Wiki in this repo.

**Comment by Zenithrium** [comment]
Ah I included dormant fungus on the wiki since it was already there. Probably should remove it for now
