### ISSUE TITLE
Item buffs do not yet have proper names or descriptions

### ISSUE THREAD

**Issue by SpoonPotato** [TeamMoonstorm/Starstorm2#167]
Buffs from items do currently display their internal name when hovered over in the UI, and have no description. Possibly not a bug, and just not yet implemented. Here's the ones I could find
BuffReactor
BuffSigil
BuffKickflip
BuffWatchMetronome
BuffChocolate
side note: it's mildly infuriating to me that these aren't in lower camel-case lmao. as long as its consistent throughout the code ig its fine, but i've gotten so used to seeing stuff typed out like buffWatchMetronome lol

**Comment by Nebby1999** [comment]
Buff descriptions and names are a better UI feature, something we don't plan to add support for atm
