### ISSUE TITLE
Issue with Ash event

### ISSUE THREAD

**Issue by ChaoticAngle** [TeamMoonstorm/Starstorm2#170]
![image_2022-11-22_235601262](https://user-images.githubusercontent.com/118873667/203471736-dcf3be5f-9cd9-4b12-8552-9981bd5a119e.png)
Started when the ash event started. Not sure what the issue is.

**Comment by ChaoticAngle** [comment]
This error pops up for every event besides Abyssal depths events

**Comment by prodzpod** [comment]
see #157
