### ISSUE TITLE
Executioner Deadly voltage ability plays "pistol shooting" animation and sounds

### ISSUE THREAD

**Issue by elislavkat** [TeamMoonstorm/Starstorm2#172]
It should be like sith from Star Wars?
![image](https://user-images.githubusercontent.com/64079137/204128255-772d400d-7c3a-43a7-aa7c-6af976755175.png)
??

https://user-images.githubusercontent.com/64079137/204128390-2186b8b7-6f43-4018-9c53-fefaee32ef5a.mp4

**Comment by swuff-star** [comment]
This is being implemented with a WIP Executioner remodel coming soon™.
