### ISSUE TITLE
Relic of Termination applying to actors it shouldn't

### ISSUE THREAD

**Issue by Mohl97** [TeamMoonstorm/Starstorm2#173]
![image](https://user-images.githubusercontent.com/13591160/204151157-3ec732ef-3d9b-4512-9404-b9c355361391.png)
Aside from it proccing on newt, resulting in eventually massive newt, I've also had it happen to the artifact shields in bulwark's ambry, causing the healthbar and encounter to start early, without player interaction. I'm running on 0.3.45 on thunderstore.

I'm kinda curious if it'll proc on mithrix before the fight, but I'm not sure if he's spawned in when you enter the room or is just dormant until you do.

**Comment by Zenithrium** [comment]
fixed in 0.3.48
