### ISSUE TITLE
Relic of Force (potentially) crashes game

### ISSUE THREAD

**Issue by MrPokemon11** [TeamMoonstorm/Starstorm2#175]
Not entirely sure if it's at fault, but given that it gives 9 related errors and then an exception related to the same function I'm confident enough to send the error log to you guys. It crashed while going through a stage transition, specifically from Siren's Call to the Bazaar. The error can be found near the bottom of the file. Something to do with ForceSkillFinalRecharge? IDK, I hope you guys can figure this out.

[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/10118511/LogOutput.log)

**Comment by Zenithrium** [comment]
earlier it looks like it failed to apply the force IL hook ([Error  :Starstorm 2 Nightly] Failed to apply Relic of Force IL Second Hook :: Line: 109, Method ForceSkillFinalRecharge) meaning some other mod affects that specific bit of IL code. which is going to be hard to fix probably

**Comment by Zenithrium** [comment]
actually, looking through it more it seems like it freaked out a lot about failing to apply the hook. i'll try look into it

**Comment by prodzpod** [comment]
@Zenithrium  idk if you pushed this but lmk if you already fixed it in your branch

**Comment by Zenithrium** [comment]
it's just in my branch right now i think

**Comment by Zenithrium** [comment]
hesitant to label this one as fixed in next update because i think i fixed the cooldowns bug but tbh there could be some other weird shit going on here
