### ISSUE TITLE
X4 stimulant

### ISSUE THREAD

**Issue by Fyrebw** [TeamMoonstorm/Starstorm2#177]
I don't know if it's the item itself or a combination of the survivor we were playing (desolator, beta branch of tesla trooper), but the log I've been looking at is saying that the item is involving a problem. Also with the sulfuric map, and the wind effects from the storm event. You can see yourself into the log under this message. 
[zipped_log.zip](https://github.com/TeamMoonstorm/Starstorm2/files/10147149/zipped_log.zip)

**Comment by Zenithrium** [comment]
gonna close this because i think this is fixed with the rework but do feel free to reopen this if im a terrible liar
