### ISSUE TITLE
Inferno doesn't count for Grand Mastery achievements

### ISSUE THREAD

**Issue by MrPokemon11** [TeamMoonstorm/Starstorm2#178]
As the title says, Inferno does not count for achievements that require you to beat the game on "Typhoon or Harder"< despite Inferno being significantly more difficult. If this could be rectified, I would appreciate it :) 
![Proof of Inferno Completion](https://user-images.githubusercontent.com/53610352/205911417-00020b54-aaed-410d-9e24-076b8988bb12.png)
![Proof of Lack of Grand Mastery](https://user-images.githubusercontent.com/53610352/205911573-59a03516-de9d-4121-9386-ef881c71ef4f.png)

**Comment by Nebby1999** [comment]
"fixed"

Quotation marks because technically inferno's scaling is 3.0 while typhoon is 3.5

Thanks @TheTimeSweeper for the pr
