### ISSUE TITLE
Greater Warbanner + Equipment Drones

### ISSUE THREAD

**Issue by Engineer664** [TeamMoonstorm/Starstorm2#181]
I have idea how it happened but 2 equipment drones with greater war banners started nonstop summoning of warbanners till my game crashed
![Risk of Rain 2 12_16_2022 11_00_07 AM](https://user-images.githubusercontent.com/120743189/208153433-c4ca6ebe-2fcf-47f1-a80f-a9fb1d9aa88d.png)

**Comment by Zenithrium** [comment]
fixed in 0.3.48
