### ISSUE TITLE
Relics of Force, and possibly Mass and Termination not working properly in MP

### ISSUE THREAD

**Issue by ethan91** [TeamMoonstorm/Starstorm2#186]
There is a current bug that is logged here where the Relic of Force gives Commando a cooldown on his primary meaning you shoot once and then have to do a reload animation, in MP when I grabbed the item that problem was put on another player who was playing Commando.  I also picked up the Relic of Termination and the marked enemies wouldn't drop items for me but seemingly random ones would drop items.

**Comment by Zenithrium** [comment]
former one is known, it's a weird issue we're not sure how to fix afaik
the second one i forgot about and will fix asap

**Comment by prodzpod** [comment]
cannot repro on my profile, test on newest version of msu and ss2, and send us your list of mods and log
