### ISSUE TITLE
Relic of Termination Crash on Umbras

### ISSUE THREAD

**Issue by Dingenerate** [TeamMoonstorm/Starstorm2#188]
Been getting consistent crashes against Umbras when carrying both a Dio's and a Relic of Termination. As far I can tell from a glance Relic of Termination keeps rapidly applying to the Umbra when it revives. I have also had the crash once when killing a Scavenger with a revive.

![image](https://user-images.githubusercontent.com/67128055/209874513-0c729fc2-b7eb-457c-a518-a9e778e2cedc.png)

**Comment by prodzpod** [comment]
term code seems to have not taken revives into account, will be fixed in april release

**Comment by Zenithrium** [comment]
oh i partially rewrote / reworked termination, it might not have this bug anymore

**Comment by Zenithrium** [comment]
oh yeah i should check this

**Comment by Zenithrium** [comment]
fixed in next update!
