### ISSUE TITLE
Captain Grand Mastery skin visual bug in character select

### ISSUE THREAD

**Issue by 446pmoctober26th** [TeamMoonstorm/Starstorm2#197]
when using the new Grand Mastery skin on the Captain, swapping to other skins keeps the new design look but changes the colors to fit the new skins color scheme. when loading into a game using a different skin it does not keep the grand mastery design, so it is only present in the character select menu.
![image](https://user-images.githubusercontent.com/114560929/210201687-db92f493-7bf9-4352-9293-ada436306175.png)
![image](https://user-images.githubusercontent.com/114560929/210201704-6c453850-e724-4a9e-9f65-4518257a98b6.png)
![image](https://user-images.githubusercontent.com/114560929/210201713-09709186-d216-4c66-bba0-036b069d5570.png)

**Comment by Nebby1999** [comment]
Install skin lobby fix
