### ISSUE TITLE
Game won't load past load screen

### ISSUE THREAD

**Issue by Thielith** [TeamMoonstorm/Starstorm2#2]
Whenever I try to run the game, the game stops loading at 26%.
I've imported the mods via r2modman and have confirmed that they've actually loaded in.

Console log:
[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/8895219/LogOutput.log)

**Comment by swuff-star** [comment]
The mod is not updated for Survivors of the Void.

**Comment by Thielith** [comment]
how do i test the new beta version that was posted on the discord then?

**Comment by swuff-star** [comment]
wait what

**Comment by Thielith** [comment]
there was a new beta version posted in the content-showcase channel by Nebby on the Starstorm 2 discord

**Comment by DarastrixJames** [comment]
> wait what

Oh have you not heard?  It was my understanding that everyone had heard.

**Comment by Nebby1999** [comment]
By the looks of it this is caused because i didnt add a submodule dependency on prefab appi (used by some effects in ss2)

Add DebugToolkit to your setup and it should fix itself, this ofc is a temporary measure, thanks for letting me know!

**Comment by gamrtiem** [comment]
yippee

**Comment by Nebby1999** [comment]
This has been fixed on the latest Alpha build on the ss2 discord, closing.
