### ISSUE TITLE
pressurized canister doesn't work and can't be disabled

### ISSUE THREAD

**Issue by DetachHead** [TeamMoonstorm/Starstorm2#202]
i tried to disable pressurized canister because it doesn't seem to do anything but it doesn't seem to be present in `com.TeamMoonstorm.Starstorm2-Nightly.cfg`. adding the following doesn't work:

```cfg
[Pressurized Canister]
Enabled = false
```

**Comment by Zenithrium** [comment]
a bit after activating it, it lets you press / hold space to go up more
also equipment disabling isn't in the current build, i think that setting just makes it so it forces you to go up during its duration

**Comment by prodzpod** [comment]
configs will be reworked in the april release, enables will be fixed with it

**Comment by Zenithrium** [comment]
reworked and configs should be fixed
