### ISSUE TITLE
Greater Warbanner Spam For Host Only

### ISSUE THREAD

**Issue by JantDarvus** [TeamMoonstorm/Starstorm2#204]
Joined a friend who was hosting. During the match, was placing down Greater Warbanners (and carefully avoiding Gestures and Equipment Drones since we already found out about that issue) and a friend reported seeing dozens of them packed together that I couldn't. Screenshot is attached.
I had definitely not done anything like that, nor could I see them, so what was causing this is a bit of a mystery.
![image](https://user-images.githubusercontent.com/45110965/211600825-4fd323dc-a85d-4da8-9e52-a2dffb162507.png)

**Comment by gamrtiem** [comment]
copy of this issue https://github.com/TeamMoonstorm/Starstorm2/issues/201

**Comment by Feldherren** [comment]
I'm not certain it's exactly #201. We'd been avoiding Gestures of the Drowned and the Equipment Drone; my friend was just placing the banners manually, and had been doing such on prior stages. Unfortunately I didn't spot these spawning, or keep count of how many banners he'd spawned on previous stages to count up if they matched and were coming forwards through the stages with us.
Additionally, whilst he had the Greater Warbanner, he couldn't see this mass of them. I could, as host. So if there's a client-side element to it, it's one that doesn't necessarily apply to the person with the banner.

**Comment by gamrtiem** [comment]
oh sorry i think i am actually like blind, seems like a very similar issues though (both affecting host only (i think)) and  are probably caused by the same thing

**Comment by Feldherren** [comment]
Yeah, they definitely seem like they could be related. Don't worry about it, easy way to read it and my friend was missing a few details from my side.

**Comment by prodzpod** [comment]
yep #201

**Comment by Feldherren** [comment]
> yep #201

We didn't have any Gestures.

**Comment by prodzpod** [comment]
in #201, it is mentioned that something about networkservers is broken- not necessarily just Gestures being involved, so it happening in MP has something to do with that
