### ISSUE TITLE
Nemesis commando M2 doesn't work in multiplayer

### ISSUE THREAD

**Issue by RazorBlado** [TeamMoonstorm/Starstorm2#207]
Non host player will not able to use M2 it won't do anything and go on cooldown

**Comment by pacomesoual** [comment]
Can confirm.
Works on host but only does the animation without any projectiles if tried on other players.
Gun m2 works tho.

**Comment by prodzpod** [comment]
did this happen before 0.3.49? nemmando will be reworked anyways but uh yeah seems like something got touched
