### ISSUE TITLE
Nemesis Commando's Ancient Scepter enhanced Decisive Strike deals no damage in multiplayer

### ISSUE THREAD

**Issue by FreezyJackalope** [TeamMoonstorm/Starstorm2#208]
I always like playing with the StandaloneAncientScepter mod and I was surprised to find out that this skill in particular was straight up broken in multiplayer. It was a shame, especially considering how cool it looks. As far as I noticed it only happens if you are not host, as testing it as a host made it work perfectly.

**Comment by prodzpod** [comment]
networking issue yeah, nemmando will be reworked in the foreseeable future. please report again if the problems persist
