### ISSUE TITLE
Relic of Termination completely breaks the Bulwarks Ambry

### ISSUE THREAD

**Issue by LilWheedle** [TeamMoonstorm/Starstorm2#210]
Relic of termination has a chance to select the Ambry "boss" and as a consequence makes it bigger. Which leads to it pushing you out of the map, unable to complete the challenge. I took a clip of it happening. I hope my reaction is enjoyable. Sorry for no audio, shadowplay didn't capture my game or discord audio so it's just me freaking out.

https://www.youtube.com/watch?v=RiRk-hVzSWU

No hard feelings y'know, it was funny. But it did ruin a good engi run. 

My bungus may have been big, but not big enough
I have failed

**Comment by prodzpod** [comment]
termination needs a blacklist of sorts (fr fr) will be done in april release

**Comment by LilWheedle** [comment]
my hero
