### ISSUE TITLE
Artifact of Swarms does not affect Nemesis Invasions

### ISSUE THREAD

**Issue by Phreelosu** [TeamMoonstorm/Starstorm2#218]
There are no errors related to this even in detailed log, I assume its just simply not yet written or something, but yea title speaks for itself

Artifact of Swarms on still spawns only 1x Nemmando, while pretty sure it should spawn 2 of them

**Comment by prodzpod** [comment]
probably related to how it spawns, will be fixed in april along with the nemmando event

**Comment by Zenithrium** [comment]
oh yea, forgot to tick this - fixed in next release!
