### ISSUE TITLE
Nemesis Commando is unlocked by default

### ISSUE THREAD

**Issue by FlightlessTuatara** [TeamMoonstorm/Starstorm2#219]
Nemesis Commando is unlocked immediately after installing the Starstorm 2 mod. No actions are required to unlock the character.

Steps to reproduce:
Create new R2Modman profile (Settings > Profile > change profile > create new).
In the new R2Modman profile, install only the Starstorm2 mod + dependencies.
Navigate to C:\Program Files (x86)\Steam\userdata\<user ID>\632360\remote\UserProfiles. Back up and delete the user profile xml.
Launch RoR2 modded. Create new user profile when prompted.
Enter single player.

Expected result:
Nemesis commando should be locked and not yet playable.

Actual result:
Nemesis commando is unlocked.

Attaching userprofile xml generated in the course of doing this.
[5cf979f1-6b0d-41c1-8d68-c52e026c19f8.xml.txt](https://github.com/TeamMoonstorm/Starstorm2/files/10712149/5cf979f1-6b0d-41c1-8d68-c52e026c19f8.xml.txt)
Suspect this was introduced at least ~3 months ago, based on some 3-month old comments on this video claiming the character was unlocked by default. https://www.youtube.com/watch?v=LL837HoYe6g

**Comment by Darkmega18** [comment]
I had this also, but paid no mind to it. I've found him in games a lot of times tho. but he usually just obliterates before I really get to see him cause of the items I have by that point...

**Comment by prodzpod** [comment]
nemmando straight up doesnt have an unlock it seems like, will be fixed maybe/? ?? if it doesnt consider it a feature

**Comment by Zenithrium** [comment]
there's no unlock condition currently since the nemfight is a little wip. I think that was the rationale

**Comment by prodzpod** [comment]
thats true nemfight a little jank. so i assume this would be fixed in the nemmando rework

**Comment by Darkmega18** [comment]
owo. he's being reworked? he usually just jumps and flies around a bit but then spontaneously combusts to my aoe or something silly. but rarely he'll turn up around the corner and instantly body me from full with his swirly special, so theres that. but more often than not he's just an exacerbation of my already well stacked loot by that point he shows up. :V

**Comment by prodzpod** [comment]
yeah nemmando and exe is being reworked
