### ISSUE TITLE
Baby's Toys Cause Negative Levels when Scrapped and Remove XP gain

### ISSUE THREAD

**Issue by KiwiKat2** [TeamMoonstorm/Starstorm2#222]

**Comment by prodzpod** [comment]
please provide a detailed steps on how you achieved this bug and the log.

**Comment by Zenithrium** [comment]
adding this as a note here
if you give yourself and then remove babys toys from yourself repeatedly at level 1 you can crash the game - also seems to jump you up to level 7 but not really? (probably negative?)
also doing this at like level 4+ makes it so the little "level + bonus" thing on the bottom left slowly inches left off the screen which is pretty funny

**Comment by Zenithrium** [comment]
more or less fixed by disabling baby's toys. The item will probably be adjusted/reworked to fix this, so I'm going to close it
