### ISSUE TITLE
relic of force gives commando's m1 a one second cooldown

### ISSUE THREAD

**Issue by lue64** [TeamMoonstorm/Starstorm2#223]
![image](https://user-images.githubusercontent.com/102778397/222996992-3f55deab-0ef1-4942-8ae0-a3353149154b.png)
it only applied after i went to a new stage however. the stage i got it on, there was no cooldown and i could shoot normally. alien head, purity, and light flux pauldron also don't affect the cooldown

**Comment by lue64** [comment]
removing the item through the console doesn't get rid of the cooldown until you move to another stage

**Comment by prodzpod** [comment]
#152
