### ISSUE TITLE
Mod says its installed but content does not appear/game does not load (stuck in loading screen at ~62%)

### ISSUE THREAD

**Issue by CrazyDiabetic** [TeamMoonstorm/Starstorm2#224]
When I load the game with the mod installed by itself, the game runs but none of the ss2 content appears. If I load it with other mods, the loading screen for the game gets stuck at roughly 62%. The BEPIN GUI error message reads as this:

[Error  : Unity Log] ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Stack trace:
System.Reflection.Assembly.GetTypes () (at <44afb4564e9347cf99a1865351ea8f4a>:IL_0000)
Moonstorm.Starstorm2.SS2Content.<Init>b__20_12 () (at <17c02fbb30ea49f0bdf05a8b1a0844cd>:IL_0015)
Moonstorm.Loaders.ContentLoader+<LoadStaticContentAsync>d__20.MoveNext () (at <e861ae2d7d7e4577a6976fe943f3e163>:IL_0038)
HG.Coroutines.ParallelProgressCoroutine+<InternalCoroutine>d__13.MoveNext () (at <73240622c0e446959aa76db30aaa7a0c>:IL_007F)
HG.Coroutines.ParallelProgressCoroutine.MoveNext () (at <73240622c0e446959aa76db30aaa7a0c>:IL_0000)
RoR2.RoR2Application+<LoadGameContent>d__70.MoveNext () (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0179)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <469e86e97fa2467ebffe49bbd6086325>:IL_0026)

**Comment by prodzpod** [comment]
Does not seem to be a SS2 issue. first, integrity check your RoR2 instance through steam or epic and disable cache from r2modman

Settings -> Toggle download cache (disable it)
Settings -> Export profile as code
Settings -> Change profile
Import -> From code
Select new profile
Start modded
Toggle the download cache (enable it)

if problems persist, make a new issue.
