### ISSUE TITLE
Stirring Soul Enabled flag (And possibly ALL config values?) not being adhered to properly.

### ISSUE THREAD

**Issue by Delfofthebla** [TeamMoonstorm/Starstorm2#225]
Using version 0.3.50 of Starstorm2 with version 1.3.0 of MoonstormSharedUtils.

I have the Stirring Soul item turned off in the config, but it still drops from Nemesis Commando every time.
My relevant config section;
```
[Stirring Soul]

## Should this item be enabled?
# Setting type: Boolean
# Default value: true
Enabled = false
```
I even tried using the RulebookUnlocker mod to disable this item and that did not work either. Stirring Soul is absurdly overpowered and I'd love to remove it from my runs, any possibly compatibility issue help and/or a future patch to fix it would be appreciated.

Upon further review, the entire config just doesn't appear to work at all. I tried setting fork damage to 3, but it still displays as 2 in game (haven't verified actual damage changes with betterUI yet but I assume it is accurate.)

For any setting, for every value, it seems that the config is being completely ignored. I tried deleting all the configs, letting the mod re-generate them on startup, and then closed the game and re-tried to change a few things. No dice.

**Comment by prodzpod** [comment]
#202
