### ISSUE TITLE
unable to disable parts using ContentDisabler

### ISSUE THREAD

**Issue by nvrfly** [TeamMoonstorm/Starstorm2#226]
Somehow it just completely overrides settings from the mod ContentDisabler, and forces all content to be loaded.

**Comment by nvrfly** [comment]
[Img](https://i.imgur.com/xnurBaO.png) - In the console they get disabled, but in the logbook, and in-game, they show up. 
Profile code is `0187003c-a5d6-2ecc-5e6f-e392771db308`

**Comment by prodzpod** [comment]
This is kind of intentional since SS2 requires all its items to be at least loaded. Ill see if i can detect configs from contentdisabler and soft-disable items like how contentdisabler disables vanilla items.

**Comment by Delfofthebla** [comment]
> This is kind of intentional since SS2 requires all its items to be at least loaded. Ill see if i can detect configs from contentdisabler and soft-disable items like how contentdisabler disables vanilla items.

Why does SS2 require all items to be loaded? I'm definitely all for any solution but that seems like a hacky way to solve the problem.

**Comment by Nebby1999** [comment]
the hacky way is disabling the items and not adding them in the content pack, lol.

In a nutshell, Starstorm2Content has nested classes that contain references to the mod's items, equipments and other definitions, whch are in turn used to get access to stuff like the instance versions of Item and Equipment classes. having these references as null (IE: not being added in the content pack) could cause issues in the future

**Comment by Hevia** [comment]
Closing since we have no immediate plans for native support of content disabling. Youre welcome to use Content Disabler or make your own mod for disabling content.
