### ISSUE TITLE
Nemesis Commando Skin Not Unlocking

### ISSUE THREAD

**Issue by Jurb109** [TeamMoonstorm/Starstorm2#227]
I obliterated 3 times on monsoon but the skin wasn’t unlocked. I also obliterated myself with a friend but, his skin for enforcer was unlocked while my skin for nemesis commando wasn’t unlocked. I did another obliteration run by myself but no skin was unlocked either.

**Comment by prodzpod** [comment]
im not sure the exact circumstances of your run so i can only guess. were you somehow dead during the obliteration? was there other mods involved? unlocks will be redone in the april release but yeah weird

**Comment by Jurb109** [comment]
> im not sure the exact circumstances of your run so i can only guess. were you somehow dead during the obliteration? was there other mods involved? unlocks will be redone in the april release but yeah weird

Other mods I’ve installed (all of them are characters and skins at the time) seem to have interfered with the unlocks. I did an obliteration run again on monsoon and typhoon with ONLY the starstorm 2 mod installed and I was able to get the skin. 

Before I got the skin though, all my runs had artifact of command with only character and skin mods (and starstorm2) installed. I obliterated on monsoon and typhoon but nothing happened, just the end screen and no unlock achievement notification on the top of the screen. Every run played out like every other. Get items, beat teleporter, next stage, and on stage 5, beat nemesis commando, and proceed like usual until stage 8. I haven’t died during any of the runs. I also did the same thing on multiplayer games which I hosted. We reached the celestial portal, with me initiating the obliteration. End screen and no achievement unlock again. I then posted the bug report but read up how mods can interfere with unlocking things and decided to have only the starstorm2 mod installed. I did the usual obliteration run on monsoon with the command artifact on, and with surprise, I got the nemesis commando skin.

**Comment by prodzpod** [comment]
please send the list of mods you usually play with, seems to be an interop

**Comment by Jurb109** [comment]
Here's the mod list, sorry for the delay.

**Comment by prodzpod** [comment]
uhh i think you sent it as an email attachment and i failed to recieve it, can you like link it or smth

**Comment by onlywancanole** [comment]
Can confirm this is happening to me as well. I can send you my modlist, which format do you prefer? I can send you my r2modman code.

**Comment by Jurb109** [comment]
> uhh i think you sent it as an email attachment and i failed to recieve it, can you like link it or smth

I hope the link works
https://docs.google.com/document/d/1cM1-TEb1-3u115gjxufItuxC7WoqvbzJYcOls5iIWzI/edit

**Comment by prodzpod** [comment]
wow something is deeply broken, ill look into it

**Comment by Hevia** [comment]
Unable to repro, closing since we havent heard of anything similar since the 0.4 release. Please reopen if this is still happening
