### ISSUE TITLE
Large floating modded items ( TeammateRevival ) on Starstorm2 characters

### ISSUE THREAD

**Issue by Djhyv2** [TeamMoonstorm/Starstorm2#229]
I have observed modded items, specifically the Charon's Obol, from TeammateRevival https://thunderstore.io/package/KosmosisDire/TeammateRevival/ shows as a very large floating model when carried by either Executioner or Nemesis Commando.

![1-000042](https://user-images.githubusercontent.com/22132164/228355232-76af0003-9dfa-4186-8226-253e378cf699.png)

I have double checked this item displays normally on default characters. (The grey disk on Huntress' left hip)

![1-000044](https://user-images.githubusercontent.com/22132164/228355502-c650f5ab-02b5-47ae-9d3c-9fd284389ea4.png)

I have also observed this item showing as a normal size, if not at a particularly visible location on modded characters such as the Paladin from PaladinMod https://thunderstore.io/package/Paladin_Alliance/PaladinMod/ (Showing here underneath his left hip only visible while running)

![1-000049](https://user-images.githubusercontent.com/22132164/228355686-13f0f752-2565-48be-9609-0d56229b0f40.png)

This behavior on other characters is what lead me to opening this issue here rather than on those mods. Please let me know if there is any additional information I can provide or a better place to log this compatibility issue.

**Comment by Zenithrium** [comment]
this is the same issue that ancient scepter had - default item displays are too large on nemmando and exe apparently. we'd need teammate revival to add custom IDRS for nemmando and exe

**Comment by prodzpod** [comment]
Yeah, please ask teammaterevival's team for this when the nemmando/exe rework drops

**Comment by Zenithrium** [comment]
I'll probably PR them like i did with scepter when we release nem and exe reworks.
