### ISSUE TITLE
Greater Warbanner and Gestures constantly placing in multiplayer.

### ISSUE THREAD

**Issue by TheCheats1** [TeamMoonstorm/Starstorm2#23]
Me and my friend were playing and then when we entered the Bazaar after Rallypoint it just happened
here is the log file
[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/9066802/LogOutput.log)
First time using Github for bug reporting so I hope I didn't screw anything up.

**Comment by leMalfaisant** [comment]
I'm late, but there doesn't seem to be enough info. Seems normal enough?
