### ISSUE TITLE
Detritive Trematode cascading "HealingSourceStack" error with Tinker's Satchel "Defibrillator"

### ISSUE THREAD

**Issue by Juanajones** [TeamMoonstorm/Starstorm2#234]
Hi,

Love the mod, found this bug that causes performance issues later into a run.

Running into a per-frame cascading error while using Starstorm 2 combined with Tinker's Satchel mod.

Seems to be triggered by Starstorm2's "Detritive Trematode" combined with TinkersSatchel's "Defibrillator" item.

It can be reproduced by grabbing 1 of each item, and then hitting an enemy until Trematode triggers - causing an error message from Tinker's Satchel relating to "HealingSourceStack".
It also sometimes triggered while having both items, and the player getting hit instead.

Log below:
[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/11231705/LogOutput.log)

Please let me know if I should also raise it with Tinker's Satchel team/creator.

Cheers,
J

**Comment by Zenithrium** [comment]
Can't seem to replicate it, at least by just applying detritive while having defib. I do see a lot of errors relating to [TKey,TValue].FindEntry but I don't remember/know where those are coming from

**Comment by Zenithrium** [comment]
Fixed the FindEntry errors, at least, Still haven't been able to replicate the HealingSourceStack error

**Comment by Hevia** [comment]
Also unable to repro the latter bug. Will close, but please reopen or file a new issue if problem keeps occurring
