### ISSUE TITLE
Config to disable equipment drops

### ISSUE THREAD

**Issue by LockeColeFF** [TeamMoonstorm/Starstorm2#235]
In the base config you can disable the item drops but not the equipment.  Can we update the config file to be able to disable those?

**Comment by swuff-star** [comment]
Implemented for next update 👍

**Comment by ThematisTM** [comment]
damnit swuff
![](https://cdn.discordapp.com/attachments/1060990816102924409/1099775379134238821/image.png)
wait this isnt my account

**Comment by Nebby1999** [comment]
ok tthats better

**Comment by LockeColeFF** [comment]
Sweet.  I was reading through the previous patch notes and saw that equipment hadn't been implemented yet.  I could've been more thorough before posting an issue.

**Comment by Zenithrium** [comment]
nah it's alright, tbh i finished it months ago, we shoulda pushed it by now
