### ISSUE TITLE
Armed Backpack doesn't disappear when the camera gets close to the player unlike other items.  

### ISSUE THREAD

**Issue by FORCED-REASSEMBLY** [TeamMoonstorm/Starstorm2#246]
[ArmedBackpack.txt](https://github.com/TeamMoonstorm/Starstorm2/files/11548545/ArmedBackpack.txt)

**Comment by FORCED-REASSEMBLY** [comment]
![image](https://github.com/TeamMoonstorm/Starstorm2/assets/99555702/a6f75047-d93b-456d-9c48-f7ae0d8d500e)

**Comment by Zenithrium** [comment]
ill look into it

**Comment by FORCED-REASSEMBLY** [comment]
I'd have a look at every item, noticed that trematode doesn't display right either.

**Comment by Zenithrium** [comment]
yep i assume they're all wrong and it's just hard to tell because it's a minor thing  
additionally on the live build they don't disappear when you usee abilities like huntress single blink but that is fixed in the dev build

**Comment by FORCED-REASSEMBLY** [comment]
Funky.

**Comment by Zenithrium** [comment]
fixed in next update
![20230523181115_1](https://github.com/TeamMoonstorm/Starstorm2/assets/64682114/03836b83-97fc-4df0-af17-e3ace9794dd0)
