### ISSUE TITLE
Scavs' item display of Trematode is completely broken lmao. I thought I just uncovered some forbidden boss.

### ISSUE THREAD

**Issue by FORCED-REASSEMBLY** [TeamMoonstorm/Starstorm2#247]
![image](https://github.com/TeamMoonstorm/Starstorm2/assets/99555702/f20de264-d688-44c1-8873-904c520365c9)
[ScavDisplay.txt](https://github.com/TeamMoonstorm/Starstorm2/files/11548929/ScavDisplay.txt)

**Comment by gamrtiem** [comment]
ss2 boss leak .,.,.......,.,....

**Comment by Zenithrium** [comment]
already fixed in next update ty for report
