### ISSUE TITLE
Stirring Soul is still unobtainable

### ISSUE THREAD

**Issue by Phreelosu** [TeamMoonstorm/Starstorm2#25]
[LogOutput_NoStirringSoul.log](https://github.com/TeamMoonstorm/Starstorm2/files/9067149/LogOutput_NoStirringSoul.log)

I'm unsure if this is intentional but I've done void fields before in the non-nightly build before SotV and Nemmando boss fight happened right after void fields right?

he dropped Stirring Soul before SotV, but now since he is coming from an event, he doesnt drop Stirring Soul

he is also not affected by Artifact of Swarms, even with swarms only one nemmando spawns.

I havent gotten to see but Nemforcer might suffer from the same fate, making Augury unobtainable as well.

I hope the log helps somewhat.

**Comment by Zenithrium** [comment]
fixed in 0.3.48
