### ISSUE TITLE
Executioner Visual Bug

### ISSUE THREAD

**Issue by MagicToads** [TeamMoonstorm/Starstorm2#254]
Found a small visual glitch that when using execution, the bubble gets left over many times and stays there permanently. 
![20230530232020_1](https://github.com/TeamMoonstorm/Starstorm2/assets/131712901/c8dd48df-fa77-4e08-ac8a-1bf741356076)

**Comment by gamrtiem** [comment]
this was fixed in 0.4.3, try updating your game

**Comment by MagicToads** [comment]
damn that was fast 0-0 good work
