### ISSUE TITLE
Needles when already 100% crit makes you unable to crit at all

### ISSUE THREAD

**Issue by NunaGrey** [TeamMoonstorm/Starstorm2#256]
I was at 100% crit... IE 9 Glasses, 1 Predatory Mask, 1 Harvest Scythe
And was critting with every hit

I picked up Needles to see what they did, and now whenever I hit an enemy, it's a normal hit... They get the needle stack infinitely. Impossible to crit. 

![Huh](https://github.com/TeamMoonstorm/Starstorm2/assets/42550426/ebf53a0b-5bdc-46f2-b39f-21748930939a)

**Comment by NunaGrey** [comment]
![image](https://github.com/TeamMoonstorm/Starstorm2/assets/42550426/1904907f-05d3-4df0-9584-7c5637c5fa2e)

**Comment by VeryCoolGamning** [comment]
Just curious, are you playing with a hypercrit mod? (makes crit chance above 100% increase crit dmg instead)
