### ISSUE TITLE
Multiplayer partners crashed, then I did next stage.

### ISSUE THREAD

**Issue by Lunat1x2** [TeamMoonstorm/Starstorm2#257]
Would like to start this off with a big thank you to the mod devs and their infinite patience with idiots like my friends and I. We have a fairly large modpack we use to play every so often, so I'm not surprised in the slightest we have some issues as soon as SS2 updates. 3 players; Executioner, Aurelion Sol, and Acrid (using voidcrid flamethrower but vanilla otherwise). Exe and ASol crashed on loading of stage 4, I crashed stage 5. I looked around at the logs myself, it mentioned Artificer flamethrowers and Constant Flow from Mystics items.

My player logs: 
[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/11609119/LogOutput.log)

Asol player logs:
[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/11609199/LogOutput.log)

**Comment by Slipskip** [comment]
From some testing earlier on just now and from reading through the plugins list in the log there's a good chance this might be an issue with Gunslinger and Starstorm not playing ball with other.

I was able to reliably reproduce a crash in single player with just those 2 installed together and every time you loaded onto a stage the Gunslinger made changes to like Rallypoint or Abyssal the game would crash on stage entry. It's strange that not everyone crashed at the same time but likely part of the same reason/issue.

**Comment by Mr-Foxtrot** [comment]
> From some testing earlier on just now and from reading through the plugins list in the log there's a good chance this might be an issue with Gunslinger and Starstorm not playing ball with other.
> 
> I was able to reliably reproduce a crash in single player with just those 2 installed together and every time you loaded onto a stage the Gunslinger made changes to like Rallypoint or Abyssal the game would crash on stage entry. It's strange that not everyone crashed at the same time but likely part of the same reason/issue.

This can be fixed for Rallypoint by disabling the changes in the config for Gunslinger, don't know about Abyssal however.

**Comment by swuff-star** [comment]
This should hopefully be fixed with 0.4.5, which addresses an issue found with compatibility between Starstorm 2 and aforementioned mods.
