### ISSUE TITLE
Item/Equip config disable not working

### ISSUE THREAD

**Issue by nuxlar** [TeamMoonstorm/Starstorm2#258]
Disabled the items and equip using the config but they still show up, here's the log.
https://pastebin.com/0KZb70j8

**Comment by Slipskip** [comment]
Adding to this. It seems only the blanket Enable/Disable All part of the config doesn't work as individually turning items off seems to still work just fine though I did only test with Armed Backpack and Greater banner.

**Comment by Zenithrium** [comment]
prod!!!!!!!!!!!!!!!!!!!!!!
