### ISSUE TITLE
Baby Toys does not reduce your levels (update. I did not read lol)

### ISSUE THREAD

**Issue by FORCED-REASSEMBLY** [TeamMoonstorm/Starstorm2#26]
[BabyToys.txt](https://github.com/TeamMoonstorm/Starstorm2/files/9075405/BabyToys.txt)

**Comment by Nebby1999** [comment]
Its impossible to reduce the levels of a single CharacterBody since the levels are team-tied instead of body-tied in ror2.

which is why baby toys gives you stats equivalent to 3 level ups.
