### ISSUE TITLE
Nemesis Commando is not taking damage in the first starting area

### ISSUE THREAD

**Issue by Fur1esss** [TeamMoonstorm/Starstorm2#263]
says what the problem is in the title, goes back to taking damage after the leaving the first area

https://github.com/TeamMoonstorm/Starstorm2/assets/94308050/5b111295-5426-4c12-b52b-a49c14195784

**Comment by Zenithrium** [comment]
it's because of that blue shield buff above your health - it makes you invulnerable. it's supposed to get cleared after leaving the portal, but I'm assuming it's not being properly removed on the live build
Just to be sure, your friend was host and you were client?

**Comment by Fur1esss** [comment]
> 

yes my friend was hosting

**Comment by Zenithrium** [comment]
gotcha, i'll try get to it asap
