### ISSUE TITLE
version crash

### ISSUE THREAD

**Issue by VividFiend** [TeamMoonstorm/Starstorm2#267]
updating starstorm to 0.4.4 crashes my game once the opening cutscene is over. it worked fine on a new profile with just starstorm installed so i guess its mods crashing together. havent used github before so im not sure how to put labels lol, sorry

![](https://cdn.discordapp.com/attachments/854865896316207108/1113888760267026592/image.png)
I've tried restarting my pc, reinstalling the mod but neither worked .
heres my logs and mod list
profile code: 01887962-2df2-0705-ce67-2a3f335e5752
logs: [LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/11630693/LogOutput.log)

**Comment by risenS** [comment]
I am also having this issue, can't use the mod on this update.
