### ISSUE TITLE
Nemmando's body parts turning black

### ISSUE THREAD

**Issue by Kazner** [TeamMoonstorm/Starstorm2#27]
After using Decisive Strike, if special skill button is not held while entire animation, nemmando's helm and sword will turn black until a use of Distant Gash.

**Comment by Nebby1999** [comment]
for anyone fixing this, this is real and has never been fixed, lol.

The code for some of the entity states modifies emmissions, and said emission modification affects the material instead of the material instance, should be easy to fix
