### ISSUE TITLE
Fog event visuals underwater is a literal flashbang

### ISSUE THREAD

**Issue by Phreelosu** [TeamMoonstorm/Starstorm2#279]
![20230605185956_1](https://github.com/TeamMoonstorm/Starstorm2/assets/97800476/b2708ac9-666a-4c6b-a155-1e94863d1224)

I mean, not a big deal but not seeing anything underwater while there is fog, especially on stages like Fogbound Lagoon this is really disruptive
Unsure if its intended

**Comment by JaceDaDorito** [comment]
uh oh

**Comment by JaceDaDorito** [comment]
wait how the hell is there fog in fbl we didnt configure it to be there yet. I have storms hard disabled for fbl.

**Comment by swuff-star** [comment]
Currently investigating. I'm guessing this issue is Fogbound Lagoon specific, as to my knowledge no other maps contain underwater sections or viewing angles?

**Comment by JaceDaDorito** [comment]
theres bits of wetland but probably not too much to worry about

**Comment by swuff-star** [comment]
fixed in next update
