### ISSUE TITLE
[Nemmando] Agile Keyword Missing from Single Tap

### ISSUE THREAD

**Issue by ToasterPig** [TeamMoonstorm/Starstorm2#283]
![gug](https://github.com/TeamMoonstorm/Starstorm2/assets/64798019/3a77bf50-3b48-4ad4-9eaf-8be5403ae030)
While hovering over Single Tap on Nemmando the description for agile appears even though agile isn't written on the ability.

**Comment by Hevia** [comment]
This can be closed @Nebby1999 @Zenithrium
