### ISSUE TITLE
Players will not respawn with Refightilization if Starstorm 2 is enabled

### ISSUE THREAD

**Issue by Bogeynator** [TeamMoonstorm/Starstorm2#285]
After one of Starstorm 2's recent updates, Refightilization will no longer respawn players after they die if both are used together. Seems to be related to Relic of Termination's recent rework (based on my VERY limited ability to read logs), but disabling the item in Starstorm 2's configs does not fix the issue.

To reproduce:
1. If in singleplayer, set EndGameWhenEverybodyDead in Refightilization's configs to false
2. Die and wait for the respawn delay

The player does not respawn.

[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/11712819/LogOutput.log)

(Edit: messed up reproduce instructions)

**Comment by Hevia** [comment]
I'll try to test this sometime soon to see whats up
