### ISSUE TITLE
No Nemmando

### ISSUE THREAD

**Issue by Hydrastorm561** [TeamMoonstorm/Starstorm2#286]
So, I might be blind (It's happened before) but for some reason I can't find nemmando anywhere on the menu screen. I've tried creating a new profile with only SS2, but I still can't find him. So, what's up?

**Comment by gamrtiem** [comment]
he is a hidden unlock, just encounter him in a loop and kill him and he'll be unlocked

**Comment by Hydrastorm561** [comment]
Oh, does he not appear on the menu as a sillouette beforehand? Noted. I assume he randomly appears as a boss, then?

**Comment by gamrtiem** [comment]
yeah,just keep in mind he can be fairly rare but he will be in a loop eventually

**Comment by Nebby1999** [comment]
Closing this for now as it's not an issue but intended
