### ISSUE TITLE
Detritive Reliquary

### ISSUE THREAD

**Issue by Hydrastorm561** [TeamMoonstorm/Starstorm2#287]
The detritive tremam... Deductive term... hmmm... the DT is causing an issue in the artifact reliquary. Once it gets to below 25% hp, the artifact reliquary becomes inflicted with the DT debuff, causing it to slowly lose HP. However, because the Reliquary loses HP, it thinks that a key is being used. Thus, it despawns all keys, and wipes them from player inventories. This is a problem, as it then takes an obscenely long time to finish the stage (about 3 days average), which makes looping via the Reliquary with the DT impossible.

**Comment by Zenithrium** [comment]
I can't replicate this but i can just hardcode it to not apply to the reliquary as that sounds like it sucked

**Comment by SilveryBards** [comment]
Same thing happened to me. Pretty sure I killed a Realgar elite (rising tides mod) and wake of vultures then gave me the ability to scar the reliquary, which pushed it past the 25% health threshold. you probably damaged it with some other source. 

Fun fact: this is currently happening to me and I figured this out a few minutes ago.

**Comment by Zenithrium** [comment]
Should be fixed in .4.6, though do open this back up if it can still occur
