### ISSUE TITLE
TeamManager.GiveExperience randomly erroring out

### ISSUE THREAD

**Issue by Phreelosu** [TeamMoonstorm/Starstorm2#288]
[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/11807483/LogOutput.log)

Completely randomly at either lvl 14, 19, 20 or 30 even the GiveExperience method errors out in an IndexOutOfRange exception form.
It does NOT stop experience gain but it does lag the game like crazy.

Starstorm2 is literally the only mod that touches TeamManager, turning off this mod solves this issue and it isn't happening anymore

**Comment by Phreelosu** [comment]
Adding onto this, I talked about this to HIFU and he said if you just hook it and check if (self.teamExperience) before actually handling the given out XP it probably will not NRE, but I honestly have no idea how and when exactly this occurs, log is there, can provide multiple logs but it really happens randomly :(

**Comment by Hevia** [comment]
Acknowledging issue just so you know its being discussed and not ignored

**Comment by Phreelosu** [comment]
can confirm this does not happen on newest version anymore, most likely due to Baby's Toys being disabled

thanks for the fix xD
