### ISSUE TITLE
When void clover try upgrade item into baby toys game cannot load stage

### ISSUE THREAD

**Issue by Kex-Energy** [TeamMoonstorm/Starstorm2#290]
From logs: [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Moonstorm.Starstorm2.Items.BabyToys+MasterBehavior.OnStackChanged (System.Int32 change) (at <f54a7c389c3144b7bb768a44549c3973>:IL_0013)
Moonstorm.Starstorm2.Items.BabyToys+MasterBehavior.CheckStackChange () (at <f54a7c389c3144b7bb768a44549c3973>:IL_0028)
Moonstorm.Starstorm2.Items.BabyToys+MasterBehavior.Inventory_onInventoryChanged () (at <f54a7c389c3144b7bb768a44549c3973>:IL_0000)
RoR2.Inventory.HandleInventoryChanged () (at <abee4f3b46184662b4d0bd0bc9965114>:IL_000A)
RoR2.Inventory.RemoveItem (RoR2.ItemIndex itemIndex, System.Int32 count) (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0076)
RoR2.CharacterMaster.TryCloverVoidUpgrades () (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0175)
RoR2.CharacterMaster.OnServerStageBegin (RoR2.Stage stage) (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0015)
RoR2.Stage.BeginServer () (at <abee4f3b46184662b4d0bd0bc9965114>:IL_001E)
RoR2.Stage.Start () (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0043)
[zipped_log.zip](https://github.com/TeamMoonstorm/Starstorm2/files/11856765/zipped_log.zip)

**Comment by Zenithrium** [comment]
more or less fixed by disabling baby's toys. The item will probably be adjusted/reworked to fix this, so I'm going to close it
