### ISSUE TITLE
Nemisis Commando not staying unlocked

### ISSUE THREAD

**Issue by GaminWithWilson** [TeamMoonstorm/Starstorm2#297]
Ive unlocked nemesis commando 2 times now but every time i close the game i have to reunlock him. its beyond frustrating

**Comment by Slipskip** [comment]
Seen this issue with others in the past for various reasons and other mods. Don't have a for sure reason as to what causes it or why but the likely issue is that your games save has some corrupted data in it which is causing it to no longer be able to save. Unfortunately that kinda means the save is bricked from what I could tell and you'll need to make a new save and use a mod like CheatUnlocks to regain the lost unlocks from making a new save

**Comment by Hevia** [comment]
We havent seen any other reports like this. Think this can be safely closed @Nebby1999 @Zenithrium

**Comment by Hevia** [comment]
@GaminWithWilson Please reopen if slipskip's help did not resolve your issue
