### ISSUE TITLE
Switching Unlock All config to "true" under SS2.Main.cfg causes a graphical ui glitch in the lobby when selecting Nemcommando, causing rows of corrupted skills to appear as you select him again and again.

### ISSUE THREAD

**Issue by eGhpGZeMqhlAIRtA1soVFK4JCDnrsxAXjirz97L** [TeamMoonstorm/Starstorm2#298]

**Comment by Slipskip** [comment]
Tested on my end and it seems to potentially be an incompat being caused by RealerCheatUnlocks while the Unlockall config is on
[LogOutput - LobbyBug.log](https://github.com/TeamMoonstorm/Starstorm2/files/12071852/LogOutput.-.LobbyBug.log)

**Comment by Zenithrium** [comment]
Prod fixed this in their latest update of RealerCheatUnlocks, so this can close
