### ISSUE TITLE
Issues with Nemesis Commando

### ISSUE THREAD

**Issue by leMalfaisant** [TeamMoonstorm/Starstorm2#3]
Apologies if I'm doing this the wrong way or something, I have about two problems to share. Decisive Strike, once finished doesn't go back to the normal camera position and stays zoomed out, and attacks that should apply Gouge just don't.

**Comment by Nebby1999** [comment]
Send log if you could so we can test this out further

**Comment by Slipskip** [comment]
Can confirm, Distant Gash and Decisive Strike don't apply Gouge and the camera stays zoomed out. Hopefully log attached properly.
[LogOutput-NemmandoNoGogue.txt](https://github.com/TeamMoonstorm/Starstorm2/files/8897181/LogOutput-NemmandoNoGogue.txt)
.
