### ISSUE TITLE
Using Nemesis Commando's alt special can cause fall damage

### ISSUE THREAD

**Issue by SnubbyNotSorry** [TeamMoonstorm/Starstorm2#302]
I just used that Decisive Strike downwards and happened to end the dash right where the ground was, which instantly killed me since I was playing on Eclipse. I am certain it was fall damage due to a mod showing me death causes.

**Comment by swuff-star** [comment]
lol sorry about the run; will fix. good catch

**Comment by Hevia** [comment]
Thanks for the footage! We'll prioritize this and hopefully get a fix out next update

**Comment by Zenithrium** [comment]
should be fixed in .5, feel free to reopen if needed!
