### ISSUE TITLE
stuck at loading screen with 0%

### ISSUE THREAD

**Issue by impaler98** [TeamMoonstorm/Starstorm2#305]
[Error  : Unity Log] MissingFieldException: Field 'RoR2.ItemTierDef.highlightPrefab' not found.
Stack trace:
Moonstorm.ItemTierModuleBase.InitializeContent (Moonstorm.ItemTierBase contentClass) (at <0c2e01bd7cf74bc199f52f73d921b323>:IL_0075)
Moonstorm.ItemTierModuleBase.AddItemTier (Moonstorm.ItemTierBase itemTier, System.Collections.Generic.Dictionary`2[TKey,TValue] dictionary) (at <0c2e01bd7cf74bc199f52f73d921b323>:IL_0000)
Moonstorm.Starstorm2.Modules.ItemTiers.<GetItemTierBases>b__7_0 (Moonstorm.ItemTierBase itemTier) (at <5a9d9c333ffd4de8b26482adb2ef6211>:IL_0000)
System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) (at <44afb4564e9347cf99a1865351ea8f4a>:IL_0024)
Moonstorm.Starstorm2.Modules.ItemTiers.GetItemTierBases () (at <5a9d9c333ffd4de8b26482adb2ef6211>:IL_000B)
Moonstorm.Starstorm2.Modules.ItemTiers.Initialize () (at <5a9d9c333ffd4de8b26482adb2ef6211>:IL_0016)
Moonstorm.Starstorm2.SS2Content+<>c.<Init>b__21_1 () (at <5a9d9c333ffd4de8b26482adb2ef6211>:IL_0005)
Moonstorm.Loaders.ContentLoader+<LoadStaticContentAsync>d__20.MoveNext () (at <0c2e01bd7cf74bc199f52f73d921b323>:IL_0038)
HG.Coroutines.ParallelProgressCoroutine+<InternalCoroutine>d__13.MoveNext () (at <73240622c0e446959aa76db30aaa7a0c>:IL_007F)
HG.Coroutines.ParallelProgressCoroutine.MoveNext () (at <73240622c0e446959aa76db30aaa7a0c>:IL_0000)
RoR2.RoR2Application+<LoadGameContent>d__70.MoveNext () (at <0f44b36eaa194934bb127b3fdd08e444>:IL_0179)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <469e86e97fa2467ebffe49bbd6086325>:IL_0026)

**Comment by Slipskip** [comment]
Please provide a full LogOutput if you can. Seeing a single error pasted out of a log often just leaves it to guesswork as to what is actually the issue.

**Comment by impaler98** [comment]
i did check files from steam and it worked

**Comment by Zenithrium** [comment]
some things that aren't inherently errors are logged as such - for example there's a few unfinished items which "return null" because they're disabled. ideally they wouldn't be errors but it's not a huge deal
