### ISSUE TITLE
Nemesis Commando is completely absent from my game

### ISSUE THREAD

**Issue by justicedragon2** [TeamMoonstorm/Starstorm2#307]
I have tried resetting all my configs, I made a new mod profile with only Starstorm 2 installed and nothing else, and for whatever reason Nemesis Commando does not show up in my runs  anymore and is not on the character select screen as a locked character or otherwise. I have searched extensively on this issue and I cannot find a solution, so any advice would be greatly appreciated. Thanks.

**Comment by gamrtiem** [comment]
the new update that revamped nemmando reset his unlock and made it hidden, currently after you kill him when he shows up post loop he'll be unlocked but you can get really unlucky with his spawn

**Comment by Hevia** [comment]
Can we close this? @Nebby1999 @Zenithrium

**Comment by Hevia** [comment]
Closing because this is a misunderstanding of how nemcommando is now hidden. Feel free to reopen if it isnt the case
