### ISSUE TITLE
Railgunner can self apply Detritive Termatode's DoT with their Concussion Device (default utility)

### ISSUE THREAD

**Issue by Zenithrium** [TeamMoonstorm/Starstorm2#31]
Was playing with a friend in multiplayer and they killed themselves with DT. Took a lucky guess and found the culprit to be the concussion device, as apparently it can apply the DoT as long as Railgunner is at low enough hp. They were the host, so it should be an issue in general, but may only apply to multiplayer.

**Comment by Heyimmodding** [comment]
Pretty easy fix. All you need to do is filter the dot by doing an if check for the playerbody. Had this happen before with another item

**Comment by Heyimmodding** [comment]
I would fix it myself but I'm taking a break from the modding community and I don't know if I'll ever be back so

**Comment by Zenithrium** [comment]
Should be fixed by #32
