### ISSUE TITLE
Wayfarer AI issues

### ISSUE THREAD

**Issue by Hevia** [TeamMoonstorm/Starstorm2#333]
Reports of Wayfarer being a spinny lad, and not the deadly boss we intended, needs adjustments. Reports can be found in discord staring here: https://discord.com/channels/753709254598328400/754133925109956675/1168665034306617455

**Comment by Hevia** [comment]
Also some balance issues with lag spikes bc 8 wayfarer spawns during shrine of mountain and projectile spam

**Comment by Priscillalala** [comment]
> Also some balance issues with lag spikes bc 8 wayfarer spawns during shrine of mountain and projectile spam

Mentioned this in the discord but that attack might make more sense as a bullet attack

**Comment by swuff-star** [comment]
issues described are either #435 or ai-related things that have been fixed internally for a while so closing
