### ISSUE TITLE
General wayfarer issues/bugs

### ISSUE THREAD

**Issue by Heyimmodding** [TeamMoonstorm/Starstorm2#335]
- the boss has zero mass, I don't know if it's intentional or what but if you hit him he just goes fucking flying 
- his boss item is untiered, not a yellow item
-the projectile prefab on the item is completely broken. I'm assuming it's the same one the boss uses since he doesn't have any projectiles either. He just kinda does nothing.
- Noise is still global. Headache machine. Please turn down the sounds too when you get a chance they are so much louder than everything else.
- do the minions even do anything? Don't think they've hit me once
- minions share sound bug, however since they're flying they can get caught in the skybox and become unkillable while blasting your ears out

**Comment by Hevia** [comment]
related: https://github.com/TeamMoonstorm/Starstorm2/issues/333

**Comment by Heyimmodding** [comment]
Partially fixed, see #340
