### ISSUE TITLE
Starstorm sending you to the wrong scene

### ISSUE THREAD

**Issue by SnolidIce** [TeamMoonstorm/Starstorm2#347]
So i play Risk of rain 2 archipelago randomizers with starstorm and recently i noticed the new update of starstorm sends you for the wrong scene

for example abandoned aqueduct is scene 17 and it is sending you to 18 instead

**Comment by Hevia** [comment]
Nobody on the dev team plays archipelago, so a log would be nice

It could be related to void shop, an unfinished map that wasnt disabled. We'll comment here when we disabled void shop and see if that fixes it.

**Comment by SnolidIce** [comment]
[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/13223997/LogOutput.log)

keep in mind its in a modpack with 87 mods and i kept disabling mods for about an hour or so and once i disabled starstorm it fixed itself

**Comment by Hevia** [comment]
Thanks! Next update should disable void shop, if that doesnt fix it please send another log over

If you know what parts of archipelago codebase controls scene randomization that might be helpful too. Very weird this issue crops up now because we arent the only mod that adds maps

**Comment by SnolidIce** [comment]
whats a void shop?

and i think the part of archipelago that doesnt control randomization. its just if you have an area unlocked it lets you go to a scene if not it doesnt let you go there

**Comment by Hevia** [comment]
Void Shop is an unfinished indev hidden realm. It was accidentally included with the 0.5 update and not disabled. Not accessible unless you console command

**Comment by SnolidIce** [comment]
interesting. alright yeah that def would of done it then. 

is there a plan for disabling that in the future patch

**Comment by Hevia** [comment]
Yes I mentioned that above already 😭

**Comment by SnolidIce** [comment]
no i ment like through config 😭😭

**Comment by Hevia** [comment]
Its being disabled outright until it is finished. When it is finished we wont be supporting disabling it via config

**Comment by SnolidIce** [comment]
sad, but alright then

**Comment by Zenithrium** [comment]
Hopefully this should be fixed in 0.5.2, but do reopen if the issue happens again. Thank you!
