### ISSUE TITLE
Haunted Lamp interaction with Executioner's M2

### ISSUE THREAD

**Issue by zeantunes97** [TeamMoonstorm/Starstorm2#350]
Not sure if an intended interaction but if you use Executioners's M2 with zero stacks while having Haunted Lamp it procs the item very fast.

**Comment by Jlouck20** [comment]
I also noticed this issue. When using the new lamp boss item on executioner, holding down both the secondary skill button and the primary skill button at the same time with zero M2 stacks will fire the spirit bolts in rapid succession, rather than after every fifth primary shot.
