### ISSUE TITLE
Executioner Special Range

### ISSUE THREAD

**Issue by Priscillalala** [TeamMoonstorm/Starstorm2#354]
Executioner's special has a very limited max range and often does not even reach range indicator.
A small amount of elevation causes the axe to impact mid air.

**Comment by swuff-star** [comment]
i was thinking about removing the range mechanic entirely and haven't it just send you down until you impact. thoughts on that?

**Comment by Heyimmodding** [comment]
Definitely think you should do that, as multiple people in the thread kinda agreed the range limit was kinda weird. refer to my feedback thread on exe for more discussion about the r

**Comment by Priscillalala** [comment]
Should either remove the range or the fixed camera cause having both is kinda redundant

**Comment by swuff-star** [comment]
range is removed next update
