### ISSUE TITLE
Lacking Baby's Toys legendary item

### ISSUE THREAD

**Issue by Jlouck20** [TeamMoonstorm/Starstorm2#359]
I have noticed that I no longer see Baby's Toys in the game. It does not show up on legendary artifact of command pools, and has not shown up randomly in the legendary item pools for 30+ hours of play since the new 0.5.0 update. Unsure if this is intentional due to bug fixes, or if it was accidentally removed.

**Comment by Hevia** [comment]
Baby toys was intentionally disabled as we rework it to fix some lag spikes it caused. Closing since we’re tracking this internally
