### ISSUE TITLE
Elite events from prior stage permentently active on Commencement

### ISSUE THREAD

**Issue by Slipskip** [TeamMoonstorm/Starstorm2#36]
[Log-EliteEvents.txt](https://github.com/TeamMoonstorm/Starstorm2/files/9241457/Log-EliteEvents.txt)
Had a glacial elite event active on Sky Meadows as it transitioned to Commencement and for the rest of the stage near every enemy was a Glacial elite. I assume the same will happen with the Blazing and Overloading events too if they happened instead.
Logs attached but this was the only error that may point towards it at line 20,642
[Error  : Unity Log] NullReferenceException
Stack trace:
Moonstorm.EventHelpers.AnnounceEvent (Moonstorm.EventHelpers+EventAnnounceInfo announceInfo) (at <063d682f64ed4bf497da1a430a6c6b6c>:IL_0000)
EntityStates.Events.EventState.OnExit () (at <063d682f64ed4bf497da1a430a6c6b6c>:IL_0066)
EntityStates.Events.GenericEliteEvent.OnExit () (at <f18a6ce700c14bc7b23d4f47b46226fa>:IL_0000)
RoR2.EntityStateMachine.OnDestroy () (at <2b2f3d5000df48ae8f94a9b49e82d786>:IL_0015)

**Comment by Zenithrium** [comment]
to semi-add to this, gups splitting while a storm is active have their children spawn as elites, same with enemies being gup ray-ed from tinker's satchel
