### ISSUE TITLE
Executioneer dash phases through textures

### ISSUE THREAD

**Issue by Atrocraz** [TeamMoonstorm/Starstorm2#360]
On sky meadows some time i was able to phase through floor with dash at this island somehow.
I got a lot of mobility, so may be it's the cause.
![image](https://github.com/TeamMoonstorm/Starstorm2/assets/130996522/c6a66289-8cfc-4106-bd95-6fdae11d2dd0)

**Comment by Zenithrium** [comment]
I'm not sure what you mean - did you fall through the floor near where you're standing?

**Comment by Zenithrium** [comment]
i'm going to close this - since it hasn't been replicated i'm gonna guess it was a weird and classic RoR2 Moment. if it happens again do reopen
