### ISSUE TITLE
Content Disabler Spoiling future content

### ISSUE THREAD

**Issue by Thingw31** [TeamMoonstorm/Starstorm2#361]
Ill be real, i dont exactly know where i should write this, and who to give it to, so this is where i decided to put it.

But Using Content Disabler mod lets people see Future skills for 2 un-used characters.
Just mentioning it in case you don't want anyone using the mod to disable other things to get spoiled.

**Comment by swuff-star** [comment]
im surprised it's only 2

**Comment by Hevia** [comment]
Closing since we can’t really stop content disabler from doing this
