### ISSUE TITLE
Haunted Lamp doesn't get corrupted by Newly Hatched Zoea

### ISSUE THREAD

**Issue by jananass** [TeamMoonstorm/Starstorm2#371]
As said in the title, I just did a run as Nemesis Commando and dropped the boss item loot from the Wayfarer, Haunted Lamp, after getting Newly Hatched Zoea, which is supposed to corrupt all yellow items.

Here is a list of the possible usecases :
- Picking up Haunted Lamp (HL) and then picking up Newly Hatched Zoea (NHZ) --> Not tested
- Picking up NHZ and then picking up HL --> HL doesn't get corrupted
- Picking up Pluripotent Lava, and then picking up HL, and then dying --> Not tested

Here is a screen, for proof : 
![image](https://github.com/TeamMoonstorm/Starstorm2/assets/34766453/9efe0c87-bccb-41f7-bb81-70f5dfda05cc)

**Comment by Zenithrium** [comment]
Should be fixed in .5.4
