### ISSUE TITLE
Nemesis Commando is nowhere to be found

### ISSUE THREAD

**Issue by justicedragon2** [TeamMoonstorm/Starstorm2#373]
I've used this mod so much that it may as well be an official expansion at this point to me. That's how much I love it. That being said, a few updates ago the 2 unlockable survivors went missing from my lobby menu. I was able to get Executioner back but no matter what I do, I've deleted every mod and done a clean install, but it doesn't seem to matter what I uninstall, what I tweak, etc... 
 Nemesis Commando is not unlockable for me. There's not even an empty slot for him in the lobby. I have no idea what causes this and help would be much appreciated. Thanks! Keep up the great work!

**Comment by swuff-star** [comment]
have you unlocked him? he's hidden until unlocked and shows up late in a run. you can check the logbook to see if the achievement is already earned.
