### ISSUE TITLE
Executioner, Ion Manipulator/Burst, Improper Interaction with Shackled Lamp, Yellow Boss Item

### ISSUE THREAD

**Issue by OriginDelta** [TeamMoonstorm/Starstorm2#374]
If Executioner has the Shackled Lamp item, and uses the Ion Manipulator/Burst secondary ability with no charges available, the Shackled Lamp will repeatedly fire at a fast rate despite no actual projectiles coming out from the secondary ability. This seems to be a bug as it does not fire that fast when using the primary ability, and I am unsure if it is even meant to fire with the secondary ability to begin with. The damage it outputs is not particularly high, so this is not a balance issue, and it is only a minor annoyance otherwise.

**Comment by Zenithrium** [comment]
wtf i swore i fixed this

**Comment by OriginDelta** [comment]
Not sure if it helps, but I am playing on version 0.5.3 which is the most updated version as far as I can tell.

**Comment by Zenithrium** [comment]
ohh, that's why noop thought it was untiered. i should probably fix it not disabling properly. as for the lamp thing my guess is that unity/github merged my fix incorrectly and some part of it got lost - itll be fixed For Real This Time in .5.4
