### ISSUE TITLE
Nemesis Mercenary not translating (PT-BR)

### ISSUE THREAD

**Issue by Kauzok** [TeamMoonstorm/Starstorm2#376]
Hello, I noticed that the translation from PT-BR for everything related to Nemesis Mercenary (achievments, skins, skills, name, etc) is not working within the game. All files are there, but something is preventing this specific part from being translated. Any idea what it could be?

**Comment by Zenithrium** [comment]
i just forgot to add them to indev..... thats on me..... they'll be real in .5.5 sorry

**Comment by Kauzok** [comment]
No prob, thanks!
