### ISSUE TITLE
Nemesis Mercenary's Proliferation duplicates Col. Droneman.

### ISSUE THREAD

**Issue by Aaron00000** [TeamMoonstorm/Starstorm2#379]
Tested with only Starstorm 2/AeroIt and their dependents. Every time you use Proliferation, Col. Droneman is duplicated. 
![20231117203648_1](https://github.com/TeamMoonstorm/Starstorm2/assets/26388052/27027fbe-4a35-461a-861d-f7a9d4e64382)
[Log.txt](https://github.com/TeamMoonstorm/Starstorm2/files/13398654/Log.txt)

**Comment by Zenithrium** [comment]
duplicate of #370 - will get to it soon ty
