### ISSUE TITLE
Executioner: Gamebreaking Glitch/Oversight

### ISSUE THREAD

**Issue by moose692011** [TeamMoonstorm/Starstorm2#382]
Using the R-Ability, the Execute, you can now fly infinitely towards a targeted location. 

However, if you use the R-Ability to a location off-stage, towards a death-plane, the Executioner will infinitely fly in the direction of the death-plane, respawn, continue flying in the same direction, respawn, then Rinse/Repeat. It is a CONSISTENT glitch and has ruined enough of my runs to the point that I can't play the character anymore. Literally unplayable.

**Comment by gamrtiem** [comment]
swuff too silly .,,,
