### ISSUE TITLE
Still missing a few translations (pt-BR)

### ISSUE THREAD

**Issue by Kauzok** [TeamMoonstorm/Starstorm2#383]
Hello, despite the 0.5.5 update having incorporated some translations, I noticed that some are still not appearing. I can provide examples: All related to the Nemesis Mercenary, the Broken Shock Drone, and the item name 'Remuneration'.

**Comment by Zenithrium** [comment]
fuck !!!!!!!!!!!!!!!!!!!!!!!!!!!!

i will look into it ty

**Comment by Zenithrium** [comment]
figured this out - some of the translation tokens didn't have commas after them, meaning any translations after got completely ignored. should be fixed - completely, and for real this time - in .5.6

**Comment by Zenithrium** [comment]
i think i also fixed this
