### ISSUE TITLE
Proliferate Causes Rex's "Seed Barrage" to Constantly Fire When Active

### ISSUE THREAD

**Issue by Jarthuzad** [TeamMoonstorm/Starstorm2#384]
Whenever a Nemesis Merc has Proliferate active, hosts who uses Rex's Seed Barrage will have it go off endlessly (with no damage until the last one) until Proliferate ends, occurs when client uses Proliferate, and host is playing Rex, does not appear to occur to clients playing Rex.

Tested with no mods but Debug Toolkit and Starstorm.
https://youtu.be/Oo_dD0RXe_Y
[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/13430542/LogOutput.log)

**Comment by Zenithrium** [comment]
should have been fixed back in .5.5 - do reopen if it's still happening!
