### ISSUE TITLE
Executioner taking friendly fire damage

### ISSUE THREAD

**Issue by Blastinburn** [TeamMoonstorm/Starstorm2#386]
Saiyans by kingrinyov are able to deal friendly fire damage to the Executioner. We tested this with just the [Vegeta](https://thunderstore.io/package/kinggrinyov/Vegeta/) and Startstorm 2 (+dependencies) and confirmed it's not caused by another incompatibility or config change.  Interestingly this only occurs with the Executioner and does not occur with other startstorm characters such as the nemesis commando.  Given the power level and size of saiyan attacks this can be extremely lethal for the executioner player.

Repro: 
Simply load into a multiplayer game with an Executioner and a Saiyan and the saiyan will be able to deal damage to the executioner player.

Logs: 
[LogOutput (Vegeta).log](https://github.com/TeamMoonstorm/Starstorm2/files/13446196/LogOutput.Vegeta.log)
[LogOutput (Executioner).log](https://github.com/TeamMoonstorm/Starstorm2/files/13446161/LogOutput.Executioner.log)

I am completely unsure which mod is causing the issue so I am submitting bug reports for both mods.

Thank you for your time.

**Comment by Hevia** [comment]
This is a funny bug. Thanks for reporting! Wel look into it

**Comment by Hevia** [comment]
The source code for the saiyans is lost according to king and when I tried to repo this sometime this summer it didnt happen. Issue could still be present but will close unless someone re-opens

and if its an issue with the saiyan mods, well king has quit modding the game for good so rip
