### ISSUE TITLE
Unknown Error with Simulacrum

### ISSUE THREAD

**Issue by Kithio** [TeamMoonstorm/Starstorm2#387]
Upon reaching Wave 10 on Simulacrum and entering the portal to go to the next stage the game stops responding and is unable to load the following stage. 

[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/13447326/LogOutput.log)

As far as I can tell, Log shows no actual data as to why the game is freezing and becoming unresponsive; Only happens when this mod is enabled

**Comment by Zenithrium** [comment]
mm. yeah there's no error in the log, and i couldn't replicate it when i tried just now

does it happen every time you try stage transition in simulacrum?

**Comment by Kithio** [comment]
It only ever happens while I have this mod enabled while in simulacrum, happened every time I went through Wave 10 stage transition. did not happen while the mod was disabled

I did find out just having the mod enabled but not "active" in the expansions list doesn't cause the problem, but having the mod enabled in the expansions list it freezes every time

**Comment by Hevia** [comment]
Try validating your game files on Steam or reinstalling the mod. I also couldn’t reproduce this error when just having SS2.

**Comment by Slipskip** [comment]
Also tried replicating it by copying the mod list from the log and everything seemed fine with default game settings on typhoon with Nemmando.
Can you potentially go into more detail on what exactly your run setups look like. Difficulty/Character/Artifacts as I do see command queue (With save) and wondering how exactly things are being done/going down that may be triggering this.

**Comment by Hevia** [comment]
No updates on this issue and nobody can repro. Closing the issue, please reopen if it still happens and you've tried the troubleshooting steps providied
