### ISSUE TITLE
Wayfarer death animations are still fucked in mp, creating what can only be described as NEXT SLIDE gameplay

### ISSUE THREAD

**Issue by Heyimmodding** [TeamMoonstorm/Starstorm2#389]
Either add a way to disable the boss, or fix this so my stage 4 isnt unplayable. Thanks

**Comment by Heyimmodding** [comment]
[nrehell.txt](https://github.com/TeamMoonstorm/Starstorm2/files/13483378/nrehell.txt)
Log

**Comment by swuff-star** [comment]
older than #435 but describes the same issue, thus closing; should be fixed next update but need more testing to be sure..
