### ISSUE TITLE
Nemforcer's Clone can negate damage from void seeds and blood pillars

### ISSUE THREAD

**Issue by bopeie** [TeamMoonstorm/Starstorm2#391]
Placing a clone from nemforcer's alt special into a void seed or blood pillar field will allow the player to stand in said field while taking no damage. Only happens if the clone is physically in the field; will go back to normal once the clone despawns.

![clone bug](https://github.com/TeamMoonstorm/Starstorm2/assets/125205553/bffe77e0-57c6-42f3-bf73-4bb8bc1661c0)

**Comment by Zenithrium** [comment]
this may have already been fixed or it's a mod interaction issue. either way i'm closing it, and if it happens again, please include a log!

**Comment by Zenithrium** [comment]
something to note - this was fixed in a dev build, but wasn't live. it will be live in just a second!
