### ISSUE TITLE
boundless pressure wont unhighlight itself

### ISSUE THREAD

**Issue by Melon-Lad** [TeamMoonstorm/Starstorm2#392]
![bild_2023-12-02_133149156](https://github.com/TeamMoonstorm/Starstorm2/assets/152700101/e44ce1d3-9ec5-426b-8001-1139716321a5)
even if you view it, it still glows

**Comment by Slipskip** [comment]
I'm guessing another mod that adds aspects to the list. You can probably just disable it with a mod like ContentDisabler as right now that aspect is unfinished and not intended to bein the public build atm

**Comment by Phreelosu** [comment]
its wolfoqol, adds aspects to the logbook, there is a config option that needs to be disabled if you use zetaspects

**Comment by Zenithrium** [comment]
oh yeah i still forgot to disable that

**Comment by Zenithrium** [comment]
i didn't forget this time
