### ISSUE TITLE
somehow my game just didnt like text so it stopped displaying it on menus

### ISSUE THREAD

**Issue by gamrtiem** [TeamMoonstorm/Starstorm2#4]
![20220613192343_1](https://user-images.githubusercontent.com/89434652/173480464-3983f95b-f72d-4549-9db4-3ea70f7cade6.jpg)
![20220613192350_1](https://user-images.githubusercontent.com/89434652/173480466-961e6314-47ee-4634-aa6b-216ceac47db3.jpg)
my game no likey :(
[log (2).txt](https://github.com/TeamMoonstorm/Starstorm2/files/8895814/log.2.txt)

**Comment by Nebby1999** [comment]
If you could recreate the error without entering so many times in a run that would help out immensly

**Comment by gamrtiem** [comment]
i’ll try to send one tomorrow if i can get it to happen again.

**Comment by QuietHydra** [comment]
Cleared stage 1 in this log before quiting to desktop
[LogOutput Full stage 1.log](https://github.com/TeamMoonstorm/Starstorm2/files/8896273/LogOutput.Full.stage.1.log)

Quit to desktop as soon as the text bug appeared which was the moment i killed an enemy
[LogOutput First kill.log](https://github.com/TeamMoonstorm/Starstorm2/files/8896280/LogOutput.First.kill.log)

**Comment by gamrtiem** [comment]
yea its literally just this above, i tried it out and same thing happened
[log.txt](https://github.com/TeamMoonstorm/Starstorm2/files/8903121/log.txt)

**Comment by Nebby1999** [comment]
I'm going to put Vale-X in charge of this one, could be that the befriend indicator is fucking things up big time, especially if these only occurr with chirr playing

**Comment by Priscillalala** [comment]
fixed in #24, apparently
