### ISSUE TITLE
Review every use of "InverseHyperbolicScaling" and make sure item descriptions are accurate

### ISSUE THREAD

**Issue by lionbryce** [TeamMoonstorm/Starstorm2#410]
Example: Field accelerator
Description: Every kill within the teleporter zone after boss is killed gain 1% (+1% per stack) [unlisted: caps at 5%]

Since InverseHyperbolicScaling is used the "1% per stack" ends up being about 1% OF 1% so 0.01% per stack.

Other Example: Prototype Jet Boots (might have the name wrong)
Says it starts at about 5m and goes up by 2.5m per stack; Doesn't mention the 15m default cap
Thanks to some funny math with InverseHyperbolicScaling it actually takes 2 to get to about 12m and 5 to get to 14m

Those were the main 2 that I could immediately tell were not working as described

Here's a desmos graph where you can fiddle with the numbers [https://www.desmos.com/calculator/9k0u201lam](https://www.desmos.com/calculator/9k0u201lam)

**Comment by swuff-star** [comment]
both items are getting reworks / stacking changes next update so _technically_ fixed. making mental note to be more careful of inversehyperbolicscaling for future though ty for pointing this out
