### ISSUE TITLE
Wayfarer's Followers Crash

### ISSUE THREAD

**Issue by ZirconExists** [TeamMoonstorm/Starstorm2#416]
The Followers run into each other causing animation bug/reset lagging game, and crashing.
suggested fix: increase hover spacing around follower's targets

**Comment by Hevia** [comment]
do you have a lot or footage?

**Comment by ZirconExists** [comment]
Good point, Im getting footage rn for you.

**Comment by ZirconExists** [comment]
Okay so the text chat is wrong, you can see as it froze and crashed at the end after i jumped on them lmfao. 
I dont think its my computer (never had this problem pre-update) or my modlist (all i had on was SS2, Skins, betterUI.)
https://github.com/TeamMoonstorm/Starstorm2/assets/156498056/5edee67d-ab79-4612-9d04-263ed75f2284

**Comment by Hevia** [comment]
@swuff-star is this still an issue or did we fix this?
