### ISSUE TITLE
Commencement is oddly reflective and bright

### ISSUE THREAD

**Issue by Feathertoes** [TeamMoonstorm/Starstorm2#419]
Correct me if I'm wrong but i don't think it's supposed to look like this
![Risk_of_Rain_2_SzVbHEWh1P](https://github.com/TeamMoonstorm/Starstorm2/assets/70271757/cc0c9763-546e-4c7b-8123-e3ff5312ad24)
![Risk_of_Rain_2_Rj1g9reVzC](https://github.com/TeamMoonstorm/Starstorm2/assets/70271757/3326ce6a-1635-4330-9421-e1f3e4b00844)

**Comment by Hevia** [comment]
Its unclear to me why this is SS2 related. Could you share what other mods you have installed?

Also this does look normal to me

**Comment by Feathertoes** [comment]
I forgot to take any screenshots but i played with only starstorm disabled with my friend and it definitely was darker when we had it off, my best guess is it's related to how the game defaults the atmosphere after a storm

**Comment by yarrowyeen** [comment]
did you have stageaesthetic?

**Comment by Feathertoes** [comment]
i didnt

**Comment by hifoomin** [comment]
That's it. I'm giving you 5 days.

**Comment by Hevia** [comment]
Ok swuff thinks this might be related to SS2 but we're unsure of the cause. No ETA on when we can get around to investigate/address this but we'll leave the ticket open until we can safely conclude this isnt SS2

**Comment by Hevia** [comment]
Thanks for reporting!
