### ISSUE TITLE
Empyrean Elite becomes unkillable with additional Elite-mods (mod-compatability)

### ISSUE THREAD

**Issue by vialra** [TeamMoonstorm/Starstorm2#421]
### "Problem"
When combined with a big addition of extra elite types (through additional mods, so no starstorm-problem and maybe lower prio), the empyrean elite becomes unkillable due to it grabbing **_all_** elite-affixes.
Fixing this issue would increase the compatability of Starstorm with other mods/larger modlists.

indeed very powerful energies begin to harmonize 😄 
![image](https://github.com/TeamMoonstorm/Starstorm2/assets/108127897/a45c6397-18d6-4851-9192-18b15d7364fc)

### Solution
Possible solutions we found when thinking about it:
- limiting the amount of elite-affixes to amount x (set in config files)
- limiting the types of elites to starstorm+basegame only
- exporting the blacklisted affixes to a config-file (tho that would be cumbersome to track with naming conventions of different creators)

### Code
From my analysis the process of loading the affixes has to be adjusted in this file [empyrean-file](https://github.com/TeamMoonstorm/Starstorm2/blob/main/SS2-Project/Assets/Starstorm2/Modules/Buffs/BuffTypes/AffixEmpyrean.cs)

either here:
```C#
foreach (EliteDef ed in EliteCatalog.eliteDefs)
{
	//shitty hardcoded case for blighted; add actual cross compat later!
	if (ed.IsAvailable() && !blacklistedEliteDefs.Contains(ed) && !body.HasBuff(ed.eliteEquipmentDef.passiveBuffDef) && ed.modifierToken != "LIT_MODIFIER_BLIGHTED")
		body.AddBuff(ed.eliteEquipmentDef.passiveBuffDef);
}
```

or here:
```C#
private static void CreateBlacklist()
{
	AddEliteToBlacklist(RoR2Content.Elites.Lunar);
	AddEliteToBlacklist(DLC1Content.Elites.Void);
}
```

**Comment by Hevia** [comment]
Yeah we're aware. Swuff plans to release a config blacklist so you can control which elites are part of Empyrean. Swuff is really busy rn so no eta on the fix but it is top of mind on things to resolve

**Comment by vialra** [comment]
Very cool ^^ Thanks for the Update/Reply :)
