### ISSUE TITLE
Needles stacks increasing even on sources of damage that don't have proc coefficients

### ISSUE THREAD

**Issue by Jikaable** [TeamMoonstorm/Starstorm2#424]
Hey,
Needles stacks are increasing even when damage is coming from sources of damage that don't have proc coefficients nor can crit (like most dots for instance)
I assume it's an oversight more so than a design choice (if it is I feel that it probably should be changed but that's another thing altogether).

**Comment by Hevia** [comment]
Needles and other items are getting complete reworks. Keeping issue open till that rework releases
