### ISSUE TITLE
Trematode doing too much damage when other sources of damage are happening at the same time

### ISSUE THREAD

**Issue by Jikaable** [TeamMoonstorm/Starstorm2#425]
Hey,
Detritive Trematode is doing its intended damage when left alone by itself but as soon as any other instance of damage is applied (proc coeff or not) it starts doing way too much damage per tick, increasing with the amount of hits between two ticks (it seems anyway, somewhat hard to test extensively)

**Comment by Hevia** [comment]
Similar comment to what I posted in the Needles issue. This item is also getting reworked. I’ll leave the issue open till those reworks release but it might be awhile on that 

Thanks for reporting!
