### ISSUE TITLE
Linux Support?

### ISSUE THREAD

**Issue by PoritzBleibfeucht** [TeamMoonstorm/Starstorm2#433]
s there a way to play this mod on Linux? I installed everything without Modloader, but the game freezes at the loading screen at 26%.

**Comment by gamrtiem** [comment]
hi, resident linux user here, id highly recommend using r2modman as it doesnt seem to have any issues loading the mod and if youre playing risk of rain 2 through proton then there shouldnt be any problem with a manual install either, maybe a mod incompatibility ? also log would be helpful !

**Comment by Hevia** [comment]
Closing because we dont support issues with manual installation. Please use a mod loader (and yeah it works with linux when using a modloader. I've also played SS2 on linux)
