### ISSUE TITLE
Assets not found

### ISSUE THREAD

**Issue by san4s204** [TeamMoonstorm/Starstorm2#434]
When I launch the game through the launcher r2modman or Thunderstore Mod Manager.
The following error is visible in the console:
[Warning:Moonstorm Shared Utils] Failed to assign Moonstorm.Starstorm2.SS2Content+Artifacts.Deviation: Asset Not Found.
and there are many such mistakes.

**Comment by Nebby1999** [comment]
Ignore these warnings as they're harmless, they'll be fixed in due time
