### ISSUE TITLE
Wayfarer boss causing insane amounts of lag

### ISSUE THREAD

**Issue by MysticaIChicken** [TeamMoonstorm/Starstorm2#435]
Disclaimer: I do not have the strongest computer and have 200+ mods, so it could be a combination of things, but on my modpack, the game consistently freezes down to <1 fps whenever a wayfarer is alive (seems to spike during one of its special attacks, but can't confirm). Additionally, wayfarer followers seem to be unusually attracted to attaching to each other, but I believe that was already mentioned in another issue. Log attached. During these lag spikes the chain of errors that are visible beginning on line 61787 is what is repeated (Also occurs earlier in the runs but this is where I died so it's easily visible toward the end)
[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/14410108/LogOutput.log)

**Comment by Hevia** [comment]
Thanks for attaching the log! This is a known issue and not your PC. You can disable wayfarer for now and just re-enable when you see the fix in the changelogs. The Content Disabler mod can be used to disable it

**Comment by MysticaIChicken** [comment]
Alright, thanks!

**Comment by Hevia** [comment]
You dont need to close it :) We'll close it when its fixed

**Comment by MysticaIChicken** [comment]
Fair enough, thanks again.

**Comment by Hevia** [comment]
Fixed for most people, and dev team is unable to repro, we have one final trick left we can implement later but I marking this as done
