### ISSUE TITLE
[Request] Make Chirr's befriended enemies cleanse themselves of previously applied debuffs when befriended.

### ISSUE THREAD

**Issue by Aaron00000** [TeamMoonstorm/Starstorm2#436]
Debuffs such as the Symbiotic Scorpion's armor debuff persist through befriending an enemy, which can significantly reduce the survivability of said friend.
![20240304125918_1](https://github.com/TeamMoonstorm/Starstorm2/assets/26388052/fd7125a4-00db-40d9-a010-ce92a38d5a33)

**Comment by nayDPz** [comment]
Thanks. Fixed for 0.6.9
