### ISSUE TITLE
Wayfarer

### ISSUE THREAD

**Issue by CasualDeer** [TeamMoonstorm/Starstorm2#438]
Every time Wayfarer shows up, the game lags considerably and often outright freezes. Seems to get worse whenever it turns invisible, but difficult to tell with the game freezing.

**Comment by Hevia** [comment]
nah its wayfarer's fault. We're lost on how to fix it. Go ahead and disable it. We'll mention in changelogs if its fixed

**Comment by CasualDeer** [comment]
> We're lost on how to fix it. Go ahead and disable it. We'll mention in changelogs if its fixed

Thanks for the quick response! Where would I go in the config editor to disable it?

Thanks again! This is my favorite mod and I would hate to disable the whole thing.

**Comment by Hevia** [comment]
profile settings -> configs -> starstorm2

if it doesnt show up there you can use content disabler mod to disable it

**Comment by swuff-star** [comment]
closing bc technically a repeat of #435 and also hopefully fixed with next update......
