### ISSUE TITLE
Scrapper UI title uses SS2_TRADER_POPUP_TEXT

### ISSUE THREAD

**Issue by aembur** [TeamMoonstorm/Starstorm2#466]
The mod changes the scrapper UI title to "Offer an item to the trader?"

![image](https://github.com/TeamMoonstorm/Starstorm2/assets/55598133/fbf11bfe-3431-41f8-94be-ab794d1faabd)

**Comment by The-Haxor** [comment]
I don't know what's up with my mods but in my case it's worse and shows this text twice.

**Comment by aembur** [comment]
The duplicated text is there since the Devotion update and appears if the only mods you have installed are Starstorm 2 and its dependencies. Personally, I just changed `SS2_TRADER_POPUP_TEXT` to `""` in the `BepInEx/plugins/TeamMoonstorm-Starstorm2/SS2Lang/en/SS2Lang_NonSurvivorBodies_en.json` file. I think not having a title is better than having two.
