### ISSUE TITLE
Prototype jet boots being activatable mid-air

### ISSUE THREAD

**Issue by Alachol** [TeamMoonstorm/Starstorm2#468]
While they do work as intended, there is a side effect wherein you can trigger them in mid-air if you get sent to the air through a method that isn't jumping. It's easily replicable by walking off an edge and "jumping" while falling, even if you don't have a hopoo feather or a double jump it still causes the explosion to occur.

**Comment by swuff-star** [comment]
technically fixed next update as part of item's rework
