### ISSUE TITLE
Coffee Bag doesn't grant buff when opening regular chests

### ISSUE THREAD

**Issue by The-Haxor** [TeamMoonstorm/Starstorm2#472]
What the title says.

I also noticed these chests show up as a bag icon when using the Radar Scanner ever since the Devotion Update. Might be related.

![Risk of Rain 2 Screenshot 2024 06 07 - 03 14 50 74](https://github.com/TeamMoonstorm/Starstorm2/assets/171461960/d9b10e8d-953e-4809-9cc2-ab05e291dfc9)
![Risk of Rain 2 Screenshot 2024 06 07 - 03 14 52 79](https://github.com/TeamMoonstorm/Starstorm2/assets/171461960/f1d12694-99b6-40b5-b454-382473f095de)

I had these mods when I first found the issue.

![335837167-65230b71-94e3-4241-9c4e-bf58d838cedd](https://github.com/TeamMoonstorm/Starstorm2/assets/171461960/02dd471f-df1d-4a3d-98d6-3fbb85f47fcf)
![335837169-842a2062-2778-43e1-9e97-0d89e069fa1f](https://github.com/TeamMoonstorm/Starstorm2/assets/171461960/15870e35-edcd-47e3-ac50-4e15456952e2)
![335837170-5fd6408f-0298-4698-a89e-edc293cdb548](https://github.com/TeamMoonstorm/Starstorm2/assets/171461960/4ace5510-35bc-4996-9ac8-d47224b4a5d5)
![335837172-e124359e-ff85-4de8-a346-76101cbf9e0c](https://github.com/TeamMoonstorm/Starstorm2/assets/171461960/3c08a26a-ed62-4f1f-9c8f-1e20f05ae1c3)

**Comment by Hevia** [comment]
closing this because we reworked coffee bag in 0.7 to a new item entirely
