### ISSUE TITLE
Disabling Nemesis Mercenary Breaks Character Select Lobby

### ISSUE THREAD

**Issue by Slipskip** [TeamMoonstorm/Starstorm2#475]
Disabling specifically NemMerc in ss2.main.cfg causes the character select lobby to break and show no selectable survivors
![image](https://github.com/TeamMoonstorm/Starstorm2/assets/104352318/e7006e4f-64e7-4050-b266-7941bff5fce2)

Only error in the log:

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Moonstorm.Starstorm2.Survivors.NemCommando.CharacterSelectBarController_Awake (On.RoR2.CharacterSelectBarController+orig_Awake orig, RoR2.CharacterSelectBarController self) (at <a44b204a334e4b6792d02d3aede75af0>:IL_0000)
DMD<>?-81262848.Hook<RoR2.CharacterSelectBarController::Awake>?370587648 (RoR2.CharacterSelectBarController ) (at <ca1464c078404223a9e558d625dccdae>:IL_0014)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
RoR2.CharacterSelectBarController.OnDisable () (at <78ca0507428e4dbea7a28fe14402f720>:IL_0000)

**Comment by swuff-star** [comment]
just needs a nullcheck in the method from the trace. that method should probably get its own dedicated class or smth instead of being in nemcommando init?
