### ISSUE TITLE
Chirr game freeze

### ISSUE THREAD

**Issue by TheScrimble** [TeamMoonstorm/Starstorm2#479]
I have yet to do testing, but it seems that when Chirr's utility drags an enemy (possibly itself, too) into terrain, the game immediately freezes. This has happened to me on two separate occasions, once in abyssal depths where accidentally grabbing an enemy caused the lift animation to get me stuck in between a couple ceiling crystals, and once on scorched acres when releasing an allied wisp into the ground (chirr was near the ground and the wisp clipped through upon release)

**Comment by Hevia** [comment]
We're aware of this bug and have it fixed in our local builds. Sadly 0.7 build involved a pretty major rewrite to MSU 2.0 which means backporting fixes is a pain. Can check with the team but likely wont be fixed till we drop 0.7 which if things go well should be this summer. Apologies for the bug!

**Comment by TheScrimble** [comment]
Oh I see
thank you! ^^

**Comment by Zenithrium** [comment]
there's a related bug where if you pick something up and then immediately throw them it breaks their movement. on players it crashes their game. should be fixed in .7 as well

**Comment by TheScrimble** [comment]
:o
good to know, I'll try and avoid that ^^

**Comment by Hevia** [comment]
0.6.8 uses the 0.7 codebase so its fixed
