### ISSUE TITLE
[0.7 Alpha] Rushrum spawncard missing

### ISSUE THREAD

**Issue by Hevia** [TeamMoonstorm/Starstorm2#485]
ITS GONE MASON

**Comment by Nebby1999** [comment]
likely fucked something up with my "upgrade scriptable objects" script MSU 2.0 has for upgrading from legacy assembly to 2.0 assmebly.

it did say to make a backup! lel

**Comment by swuff-star** [comment]
will reimpl once im home ig. have any other spawncards been noticed to be missing? i have a strong feeling interactables may be but cant verify myself atm

**Comment by swuff-star** [comment]
yea im thinkin hes back
