### ISSUE TITLE
[0.7 Alpha] Elite director causing spam in console

### ISSUE THREAD

**Issue by Hevia** [TeamMoonstorm/Starstorm2#493]
Logs have been shared in playtesting server

**Comment by Hevia** [comment]
[LogOutput.log](https://github.com/user-attachments/files/16565766/LogOutput.log)

**Comment by Hevia** [comment]
void fields is unplayable with this spam

**Comment by Hevia** [comment]
seems to be related to lunar gambler elite?

**Comment by swuff-star** [comment]
fixed on my branch just needs merged

**Comment by swuff-star** [comment]
fixed in void fields and SHOULD BE fixed elsewhere but im scared itll somehow show up somewhere again so just keep an eye out ig..
