### ISSUE TITLE
[0.7 Alpha] Remuneration GONE???

### ISSUE THREAD

**Issue by Hevia** [TeamMoonstorm/Starstorm2#495]
Probably something wrong with itemdef idk, needs fixing

**Comment by nayDPz** [comment]
its remuneration dumbass

**Comment by Hevia** [comment]
See? This is whats wrong with America, ror2 modders cant spell, SHAME, if I became president we'd fix BIDEN's america, we'd fix it good, yeah, when I was president EVERYONE could spell remuneration, but not anymore, you cant do that anymore no you cant
