### ISSUE TITLE
Typhoon Tooltip Displaying Incorrectly

### ISSUE THREAD

**Issue by Slipskip** [TeamMoonstorm/Starstorm2#5]
![TyphoonDisplay](https://user-images.githubusercontent.com/104352318/173513627-e52b84c2-2ebc-4c31-b80a-6ce3739a9386.png)
Picture basically showcases it but Typhoons Difficulty tooltip isn't displaying like vanilla and other modded difficulties in the character select lobby. Log attached just incase.
[LogOutput-TyphoonDisplay.txt](https://github.com/TeamMoonstorm/Starstorm2/files/8897233/LogOutput-TyphoonDisplay.txt)
.

**Comment by Nebby1999** [comment]
Fixed in the newest alpha release of SS2.

Link (Requires access to the SS2 discord server): https://discordapp.com/channels/753709254598328400/754484105584050216/993600660199198881
