### ISSUE TITLE
S.T.A.R.S badge on Monsoon started appearing

### ISSUE THREAD

**Issue by MeatSackAttack** [TeamMoonstorm/Starstorm2#501]
I'm not sure if this is a bug, or an intended mechanic, but I used to play all the time on monsoon/typhoon, and recently it started putting the S.T.A.R.S badge in my inventory at run start. I'm not seeing a way to disable it in config, and not sure if this Is even supposed to be happening, but feedback would be helpful, because I don't see anyone else talking about this.

-Again sorry if this is the wrong place to post this, as to the uncertainty of it being a bug, or me just being stupid.

**Comment by Slipskip** [comment]
This isn't related to Starstorm2 but the Character mod Hunk. You can revert to a prior version of Hunk on the mod manager by downloading it again and selecting an older version or by going on the mod page on Thunderstore and clicking on the versions tab and downloading an older version that way.

**Comment by swuff-star** [comment]
not related to starstorm 2. downgrade hunk mod
