### ISSUE TITLE
The survivors have not been translated into Russian until the end

### ISSUE THREAD

**Issue by TYRBOBORYA** [TeamMoonstorm/Starstorm2#504]
Nemesis mercenary skills are not translated,  Executioner 2 skills are displayed incorrectly and are not translated, Cheer skills are also not translated
![image](https://github.com/user-attachments/assets/c4888023-955d-407c-be34-82f412232920)
![image](https://github.com/user-attachments/assets/d6cadfdf-a498-4ae6-bbc5-0e27304cfc8b)
![image](https://github.com/user-attachments/assets/e9f17929-1c03-4640-bff3-d0fead01737c)
![image](https://github.com/user-attachments/assets/7118f43e-c52e-4943-88dc-f1b7bf3d5981)
![image](https://github.com/user-attachments/assets/96b8b422-5085-41ab-ad57-d14a9a9c465a)
![image](https://github.com/user-attachments/assets/abdbfcd7-5c76-4f01-af1e-ff82b553d075)
![image](https://github.com/user-attachments/assets/b3557b14-8134-417c-997a-2a7233dae00d)
![image](https://github.com/user-attachments/assets/dc7f7eb3-4f62-451e-a2c7-362e92af380b)
![image](https://github.com/user-attachments/assets/8dc3e894-8410-4592-a635-c2a987355a14)
![image](https://github.com/user-attachments/assets/57cb6e4f-a255-4f09-bba0-d3de05156887)
![image](https://github.com/user-attachments/assets/ef56c5bf-497d-4ece-ab65-c4cb4792dc08)

**Comment by Hevia** [comment]
We sadly dont handle translations, community members provide them for us which we're grateful for (the team also speaks english/spanish). If you'd like to translate let us know! Otherwise closing since we cant fix this
