### ISSUE TITLE
Nemesis commando not spawning

### ISSUE THREAD

**Issue by YuriiZakharov** [TeamMoonstorm/Starstorm2#509]
I have tried to go through fields on 1-st stage, on 3-rd stage, enter and leave and enter clear and leave, tried going on a loop, play as commando and other characters, and still nemesis commando didn't spawn

**Comment by Slipskip** [comment]
To clarify, When you entered Void Fields did you pick up an item called Condemned Bond that's hidden on the stage? If not you need to find that item to trigger this mods Nemesis Invasions. If yes then please send a logoutput which you can find by navigating to the bepinex folder that mods are stored. On the mod manager you can get there by going to settings > locations > browse profile folder > open bepinex folder and the LogOutput.txt will be inside that folder.

**Comment by swuff-star** [comment]
closing for now since spawning was re-written in 0.6.8 and should generally be functional. please re-open / re-report if experiencing otherwise
