### ISSUE TITLE
Cannot join Multiplayer game via Steam friend list

### ISSUE THREAD

**Issue by LeoBesimo** [TeamMoonstorm/Starstorm2#515]
Installed Mods:
Starstorm2 v.0.6.7 with dependencies
LookingGlass v1.8.5 with dependencies

Game returns to Main menu when changing from multiplayer lobby to character select.

BepInEx Logfile:
[LogOutput.log](https://github.com/user-attachments/files/16737803/LogOutput.log)

**Comment by Hevia** [comment]
Hmm not sure if a recent lookingglass update caused this, nothing in the log tells me its an error with either mod. I did see some folks reporting issues with Steam in the modcord earlier today. If it doesnt work later ill see if we can repro

**Comment by Slipskip** [comment]
This is very likely an issue with steam itself as even people in vanilla are unable able to join each other presently which has also affected a bunch of other games on steam

If it is then the work around is unfortunately using Epic Games Crossplay till valve fixes whatever it was they broke two days ago.

**Comment by swuff-star** [comment]
could you also use lobby codes maybe? idk how reliant on steam that is

**Comment by LeoBesimo** [comment]
i just tried and it works with the lobby codes so it probably is a problem with steam
