### ISSUE TITLE
Loading stuck at 10%

### ISSUE THREAD

**Issue by BingoRly** [TeamMoonstorm/Starstorm2#517]
Well, loading just stuck at 10%
[LogOutput.log](https://github.com/user-attachments/files/16788872/LogOutput.log)

Thanky-thanky for your answer in advance ^^

**Comment by Hevia** [comment]
The recent DLC broke mods, nothing we can do till modding APIs are updated and fixed, just gotta wait

**Comment by BingoRly** [comment]
Thank you so much for such an fast answer ^^
