### ISSUE TITLE
Update for SOTS

### ISSUE THREAD

**Issue by Tempertibbs** [TeamMoonstorm/Starstorm2#518]
This is my favorite mod for the game so was wondering if this is going to get updated for the new DLC?

**Comment by swuff-star** [comment]
yes

**Comment by DandyDidIt** [comment]
Out of curiosity do we have any sort of timeline on that? I understand how big of a project SS2 and that it probably is the farthest from a simple fix so I'm not looking to rush it but I was just hoping we had any sort of timeline to reference (even if only vague)

**Comment by DandyDidIt** [comment]
Much appreciated and hope things go smoothly! Ya'll put out the best part of the game without a doubt.
