### ISSUE TITLE
Problem on startup regarding monster editor

### ISSUE THREAD

**Issue by Johaxan163** [TeamMoonstorm/Starstorm2#522]
i have been having problems with using the starstorm mod to not say that the game wont open, here the section of the log output related to the problem.

also i should say i am using a downpatched version of the game

[Info   :Starstorm 2] Initializing Scenes.
[Info   :Starstorm 2] Initializing Item Tiers...
[Debug  :RoR2BepInExPack] Hook added by assembly: Ivyl.dll for: RoR2.Util.IsPrefab
[Debug  :RoR2BepInExPack] Hook added by assembly: R2API.ArtifactCode.dll for: RoR2.PortalDialerButtonController.OnStartClient
[Debug  :RoR2BepInExPack] Hook added by assembly: R2API.ArtifactCode.dll for: RoR2.PortalDialerController.Awake
[Debug  :RoR2BepInExPack] Hook added by assembly: R2API.ArtifactCode.dll for: RoR2.PortalDialerController.PerformActionServer
[Debug  :RoR2BepInExPack] Hook added by assembly: Ivyl.dll for: RoR2.EquipmentSlot.PerformEquipmentAction
[Info   :Starstorm 2] Initializing Items...
[Debug  :RoR2BepInExPack] Hook added by assembly: Starstorm2.dll for: RoR2.PickupDisplay.RebuildModel
[Debug  :RoR2BepInExPack] Hook added by assembly: Starstorm2.dll for: RoR2.Items.ContagiousItemManager.Init
[Debug  :RoR2BepInExPack] Hook added by assembly: Starstorm2.dll for: RoR2.Util.GetBestBodyName
[Debug  :RoR2BepInExPack] Hook added by assembly: Starstorm2.dll for: RoR2.GenericSkill.CalculateFinalRechargeInterval
[Debug  :RoR2BepInExPack] Hook added by assembly: Starstorm2.dll for: RoR2.Util.GetBestBodyName
[Debug  :RoR2BepInExPack] Hook added by assembly: Starstorm2.dll for: RoR2.TeamComponent.SetupIndicator
[Debug  :RoR2BepInExPack] Hook added by assembly: Starstorm2.dll for: RoR2.GlobalEventManager.OnInteractionBegin
[Info   :Starstorm 2] found lightobj
[Info   :Starstorm 2] found light compontent
[Error  : Unity Log] ItemTierDef 'Sibylline' has a tier of 'AssignedAtRuntime'.  Attempting to fix...
[Info   :Starstorm 2] Initializing Equipments...
[Message:R2API.TempVisualEffect] Added new TemporaryVisualEffect: R2API.TempVisualEffectAPI+TemporaryVisualEffectInfo
[Debug  :RoR2BepInExPack] Hook added by assembly: Starstorm2.dll for: RoR2.GenericSkill.RunRecharge
[Info   :Starstorm 2] Initializing Buffs.
[Debug  :RoR2BepInExPack] Hook added by assembly: Starstorm2.dll for: RoR2.Util.GetBestBodyName
[Debug  :RoR2BepInExPack] Hook added by assembly: Starstorm2.dll for: RoR2.CharacterBody.RecalculateStats
[Debug  :RoR2BepInExPack] Hook added by assembly:  for: RoR2.CharacterBody.RecalculateStats
[Info   : R2API.Dot] Custom Dot (Index: 14) that uses Buff : BuffBane added
[Debug  :RoR2BepInExPack] Hook added by assembly: Starstorm2.dll for: RoR2.HealthComponent.GetHealthBarValues
[Info   : R2API.Dot] Custom Dot (Index: 15) that uses Buff : BuffChirrConvert added
[Debug  :RoR2BepInExPack] Hook added by assembly: Starstorm2.dll for: RoR2.GenericSkill.RunRecharge
[Info   : R2API.Dot] Custom Dot (Index: 16) that uses Buff : BuffGouge added
[Debug  :RoR2BepInExPack] Hook added by assembly: Starstorm2.dll for: RoR2.HealthComponent.TakeDamage
[Info   : R2API.Dot] Custom Dot (Index: 17) that uses Buff : BuffInsecticide added
[Debug  :RoR2BepInExPack] Hook added by assembly: Starstorm2.dll for: EntityStates.AI.Walker.Combat.GenerateBodyInputs
[Debug  :RoR2BepInExPack] Hook added by assembly:  for: EntityStates.AI.Walker.Combat.GenerateBodyInputs
[Info   : R2API.Dot] Custom Dot (Index: 18) that uses Buff : BuffTrematodes added
[Info   :Starstorm 2] Initializing DamageTypes.
[Debug  :RoR2BepInExPack] Hook added by assembly: Starstorm2.dll for: RoR2.Projectile.ProjectileSingleTargetImpact.OnProjectileImpact
[Info   :Starstorm 2] Initializing Projectiles.
[Info   :Starstorm 2] Initializing Elites...
[Info   :Starstorm 2] Initializing Bodies.
[Debug  :Moonstorm Shared Utils] Getting the Characters found inside Starstorm2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null... :: Line: 115, Method GetCharacterBases
[Error  : Unity Log] TypeLoadException: Invalid type Moonstorm.MSMonsterDirectorCard for instance field Moonstorm.Starstorm2.Monsters.Lamp:defaultCard
Stack trace:
System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) (at <44afb4564e9347cf99a1865351ea8f4a>:IL_001B)
System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) (at <44afb4564e9347cf99a1865351ea8f4a>:IL_00A8)
System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) (at <44afb4564e9347cf99a1865351ea8f4a>:IL_0009)
System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) (at <44afb4564e9347cf99a1865351ea8f4a>:IL_0027)
System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) (at <44afb4564e9347cf99a1865351ea8f4a>:IL_0020)
System.Activator.CreateInstance (System.Type type) (at <44afb4564e9347cf99a1865351ea8f4a>:IL_0000)
Moonstorm.ModuleBase`1+<>c__1`1[T,T].<GetContentClasses>b__1_3 (System.Type type) (at <1cfdebd330eb4d3393de29628234c4d3>:IL_0000)
System.Linq.Enumerable+WhereSelectArrayIterator`2[TSource,TResult].MoveNext () (at <55b3683038794c198a24e8a1362bfc61>:IL_0041)
System.Linq.Enumerable+WhereEnumerableIterator`1[TSource].MoveNext () (at <55b3683038794c198a24e8a1362bfc61>:IL_004E)
System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) (at <44afb4564e9347cf99a1865351ea8f4a>:IL_0077)
System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <55b3683038794c198a24e8a1362bfc61>:IL_000E)
Moonstorm.Starstorm2.Modules.Characters.GetCharacterBases () (at <07c13b169c944284969256cbd1556e65>:IL_002A)
Moonstorm.Starstorm2.Modules.Characters.Initialize () (at <07c13b169c944284969256cbd1556e65>:IL_0016)
Moonstorm.Starstorm2.SS2Content+<>c.<Init>b__22_8 () (at <07c13b169c944284969256cbd1556e65>:IL_0005)
Moonstorm.Loaders.ContentLoader+<LoadStaticContentAsync>d__20.MoveNext () (at <1cfdebd330eb4d3393de29628234c4d3>:IL_0038)
HG.Coroutines.ParallelProgressCoroutine+<InternalCoroutine>d__13.MoveNext () (at <0ad201b9b2804a53b3d7f599d5d0f90e>:IL_007F)
HG.Coroutines.ParallelProgressCoroutine.MoveNext () (at <0ad201b9b2804a53b3d7f599d5d0f90e>:IL_0000)
RoR2.RoR2Application+<LoadGameContent>d__70.MoveNext () (at <78ca0507428e4dbea7a28fe14402f720>:IL_0179)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <85d1d3e7744a4a47b5f51883bf40bba2>:IL_0026)

**Comment by Hevia** [comment]
We wont be supporting the downpatched version of the game and have started work on the SOTS patch, I am sorry youre having issues!

If you join the discord you can download the 0.6.8-indev version along with MSU 2.0-indev (both only work on downpatch) and see if that works for you. Otherwise youll just have to wait for us to drop the SOTS patch in a few weeks

**Comment by Johaxan163** [comment]
were are those version posted on the discord_, i have been looking for them but i have not found them

**Comment by gamrtiem** [comment]
theyre in the #content-showcase channel if yoy scroll up a bit (https://discord.com/channels/753709254598328400/754484105584050216/1277869708573675542)

**Comment by Johaxan163** [comment]
thanks
