### ISSUE TITLE
Console log spam on release build

### ISSUE THREAD

**Issue by Hevia** [TeamMoonstorm/Starstorm2#523]
Everyone in SS2 server please tag Nebby so they have your energy to fix this!

**Comment by gamrtiem** [comment]
@Nebby1999 plead blast !!!!!

**Comment by Hevia** [comment]
You gotta tag Nebby in SS2 server discussions channel for this to work

**Comment by Nebby1999** [comment]
Hey its me goku!

i've fixed it, thanks for the help! that genki-dama will surely defeat claptrap!
