### ISSUE TITLE
title screen is too laggy and the ss2 characters do not appear in the game at all.

### ISSUE THREAD

**Issue by FORCED-REASSEMBLY** [TeamMoonstorm/Starstorm2#53]
[SS2.txt](https://github.com/TeamMoonstorm/Starstorm2/files/9388975/SS2.txt)

**Comment by FORCED-REASSEMBLY** [comment]
Update, no ss2 models appear in game. So no items, characters and anything else that this build has added

**Comment by FORCED-REASSEMBLY** [comment]
2nd update. Dying or doing something (i have no idea what) brings everything back.

**Comment by Heyimmodding** [comment]
fixed in the new alpha
