### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by Vaurren** [TeamMoonstorm/Starstorm2#538]
Consistent error on startup. This is on a fresh install. I can't make heads or tails of the error. apologies for my code illiteracy but this is as much as I can understand about it not loading.
[LogOutput.log](https://github.com/user-attachments/files/17053017/LogOutput.log)

**Comment by Hevia** [comment]
here is the profile code we used during testing: 01920852-8c8a-9f55-f3ce-964d2457a072

import that, then reinstall ss2, but also make sure to clear your download cache in profile settings before doing so. Your error doesnt seem related to missing dependencies afaik

**Comment by Vaurren** [comment]
That worked? Must be something with the cache. Thanks for the help
