### ISSUE TITLE
Chirr can befriend multiple enemies 

### ISSUE THREAD

**Issue by FORCED-REASSEMBLY** [TeamMoonstorm/Starstorm2#55]
[Chirr.txt](https://github.com/TeamMoonstorm/Starstorm2/files/9389304/Chirr.txt)

**Comment by Heyimmodding** [comment]
Chirr isn't really supposed to be 100% working, but I'm sure vale will get to this eventually

**Comment by prodzpod** [comment]
chirr will be reworked in the foreseeable future, please report again when the issue persists after the rework
