### ISSUE TITLE
formatting errors in item descriptions

### ISSUE THREAD

**Issue by Phreelosu** [TeamMoonstorm/Starstorm2#555]
![image](https://github.com/user-attachments/assets/04f50eb2-60cb-40a2-b752-cabb6f7db7fc)

game starts up in english and produces this bug, if I switch to any other language and then back to english the bug is gone and everything is formatted normally

not a game breaking bug but definitely inconvenient and immersion breaking

**Comment by Nebby1999** [comment]
Could you submit a log? this might be an issue upstream on my end

**Comment by Phreelosu** [comment]
closing because I suddenly cant replicate it even after restarting the game 3 times so, might send log whenever it happens again, but until then I'll close this

**Comment by Phreelosu** [comment]
[LogOutput.log](https://github.com/user-attachments/files/17114387/LogOutput.log)
![image](https://github.com/user-attachments/assets/4efc2368-816f-4c94-ba75-fa08d20ece7c)

replicated randomly
