### ISSUE TITLE
[Chirr] Dropping abducted enemies does not work properly.

### ISSUE THREAD

**Issue by Minomutchi** [TeamMoonstorm/Starstorm2#569]
Most of the time I Abduct an enemy as Chirr and drop them to the ground, instead of instantly triggering the damaging impact upon landing, they will either freeze in place where they were dropped or slide across the floor, with the impact randomly triggering after 1-10 seconds of sliding or being stuck in place.

> Profile code: 01921579-1d26-844c-501e-ab0fa3aeb2c0 

https://github.com/user-attachments/assets/fc3a0e9b-5760-402f-a4ce-39c04cc58166

**Comment by Hevia** [comment]
This is caused by the known issue we mentioned on the TS page and the known issue channel in the discord. It’s sadly a vanilla bug that GBX needs to fix. You can download the EnemyImportance mod as a stop gap though

**Comment by Minomutchi** [comment]
Totally missed that line on the Thunderstore page, my bad. Installed EnemyImportance and it seems to work fine for now, thank you °3° <3
