### ISSUE TITLE
Needles stills needs 5 stacks to proc instead of 2

### ISSUE THREAD

**Issue by Slipskip** [TeamMoonstorm/Starstorm2#57]
![20220821185304_1](https://user-images.githubusercontent.com/104352318/185804407-5686df70-8e6c-47f0-836f-dd08a4df0edf.jpg)
[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/9389704/LogOutput.log)

Self-explanatory really. Still needs 5 stacks instead of 2 as of the 21/08/2022 build. Item description also still states needing 5 stacks to proc.

**Comment by Priscillalala** [comment]
might be your config not updating?

**Comment by Slipskip** [comment]
Yeah seems so. Still on 5 instead despite the default being 2 now.

**Comment by leMalfaisant** [comment]
youll need to delete the config first i believe, iirc trematode doesn't do damage as well unless you delete it too?

**Comment by Slipskip** [comment]
Yeah clearing the config and letting the game regenerate it solved the issue. I think Trematode was doing damage for me in an earlier run but if it wasn't it will now.
