### ISSUE TITLE
multiple wayfarer spawns making game insanely laggy

### ISSUE THREAD

**Issue by why-is-Kritte-not-avalivble** [TeamMoonstorm/Starstorm2#575]
if multiple wayfarers spawn and attack, they will cause the game to drop to 10fps

**Comment by yarrowyeen** [comment]
war.. war never changes..
https://github.com/TeamMoonstorm/Starstorm2/issues/435
https://github.com/TeamMoonstorm/Starstorm2/issues/438

**Comment by Hevia** [comment]
a fixed for zetaspects dropped that addresses wayfarer lag caused by using ss2 + aetherium + zetsaspects together: https://thunderstore.io/package/William758/ZetAspects/
