### ISSUE TITLE
Nemesis Mercenary Model twitching rapidly, visual bug

### ISSUE THREAD

**Issue by CalvinJacobsen** [TeamMoonstorm/Starstorm2#579]
Breif Description:

https://github.com/user-attachments/assets/50d470bf-e949-44fd-a192-b53609ffe29e
[LogOutput.log](https://github.com/user-attachments/files/17117071/LogOutput.log)

Basically as you can see from the video above, I'm getting a visual bug where Nemesis Mercenary is twitching rapidly.
This always happens no matter what stage I'm on. I tried adjusting my framerate as well, but that didn't seem to do anything either.
Not sure if any of my other mods are causing this, but hope the video helps a little bit.
There is no error associated with this visual bug I'm assuming, but my logoutput file is included, if it helps too.

**Comment by nayDPz** [comment]
Fixed for next patch. Thanks for the report
