### ISSUE TITLE
Nemmando Decisive Strike Softlock (0.6.9)

### ISSUE THREAD

**Issue by proboscismonky** [TeamMoonstorm/Starstorm2#588]
Using decisive strike for the very first time after booting up the game makes you unable to move or do anything. Works fine if you exit to menu and start a new game. The log also contains a ton of errors from when I was unable to move. Bug does not occur if hornet or soldier skins are used.
[NemmandoLog.zip](https://github.com/user-attachments/files/17183102/NemmandoLog.zip)

**Comment by jonathanvupham** [comment]
also having this
vid: 
![image](https://github.com/user-attachments/assets/81b40d32-225f-4272-9452-cdf1b763c3df)

**Comment by DamageMaximo** [comment]
same is happening to me, the log keeps repeating this:

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
EntityStates.Nemmando.BossAttackCharge.FixedUpdate () (at <e0896b705c504f7e9ddc76836950b7d7>:IL_0043)
RoR2.EntityStateMachine.ManagedFixedUpdate (System.Single deltaTime) (at <a149dbd7438a4e73b97d6600b3a2bbd4>:IL_001D)
RoR2.EntityStateMachine.FixedUpdate () (at <a149dbd7438a4e73b97d6600b3a2bbd4>:IL_0006)

**Comment by proboscismonky** [comment]
Fixed in 0.6.10
