### ISSUE TITLE
cant load the game, stuck at 55%

### ISSUE THREAD

**Issue by CptScrub** [TeamMoonstorm/Starstorm2#591]
when i try to load in game using R2modman, i get stuck at 55%, even with only starstorm2 as mod.

i get following errorcode;

[Error  : Unity Log] TypeLoadException: Could not load type of field 'R2API.DamageAPI:damageTypeHolders' (2) due to: Could not resolve type with token 01000018 from typeref (expected class 'RoR2BepInExPack.Utilities.FixedConditionalWeakTable`2' in assembly 'RoR2BepInExPack, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null') assembly:RoR2BepInExPack, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null type:RoR2BepInExPack.Utilities.FixedConditionalWeakTable`2 member:(null)
Stack trace:
SS2.Survivors.Chirr.RegisterConfuseOnHit () (at <e0896b705c504f7e9ddc76836950b7d7>:IL_0000)
SS2.Survivors.Chirr.Initialize () (at <e0896b705c504f7e9ddc76836950b7d7>:IL_004D)
MSU.CharacterModule.InitializeCharacters (BepInEx.BaseUnityPlugin plugin, System.Collections.Generic.List`1[T] bodies, MSU.IContentPieceProvider`1[T] provider) (at D:/RoR2Related/Projects/MSUDev/Packages/teammoonstorm-moonstormsharedutils/Runtime/Code/Modules/CharacterModule.cs:137)
MSU.CharacterModule+<InitializeCharactersFromProvider>d__14.MoveNext () (at D:/RoR2Related/Projects/MSUDev/Packages/teammoonstorm-moonstormsharedutils/Runtime/Code/Modules/CharacterModule.cs:126)
MSU.CharacterModule+<InitializeCharacters>d__12.MoveNext () (at D:/RoR2Related/Projects/MSUDev/Packages/teammoonstorm-moonstormsharedutils/Runtime/Code/Modules/CharacterModule.cs:83)
SS2.SS2Content+<LoadStaticContentAsync>d__12.MoveNext () (at <e0896b705c504f7e9ddc76836950b7d7>:IL_0129)
HG.Coroutines.ParallelProgressCoroutine+<InternalCoroutine>d__13.MoveNext () (at <50c819d11e6e4629a088087b9de5727d>:IL_007F)
HG.Coroutines.ParallelProgressCoroutine.MoveNext () (at <50c819d11e6e4629a088087b9de5727d>:IL_0000)
RoR2.RoR2Application+<LoadGameContent>d__112.MoveNext () (at <a149dbd7438a4e73b97d6600b3a2bbd4>:IL_013C)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <a20b3695b7ce4017b7981f9d06962bd1>:IL_0026)

**Comment by Slipskip** [comment]
Looks like a similar case to other logs posted and should be fixed the same way. On the mod manager go to settings > debugging > toggle download cache off and then to profile > export as code  and then go to the profile select screen with that code and click > import > from code > paste code. With any luck it should just work and it's some weirdness with the original profile or its downloads as it's complaining about ror2bepinexpack.

Out of curiosity though could you post the full log as well ?

**Comment by CptScrub** [comment]
what a livesaver you are bro, followed the steps and it worked out perfect, want me to go grab the full log aswel still?
