### ISSUE TITLE
Executioner Camera Bug

### ISSUE THREAD

**Issue by Slipskip** [TeamMoonstorm/Starstorm2#6]
Using the special Execution causes the camera to stay zoomed out and causes the cross hair to disappear
[LogOutput-ExecutionerCamera.txt](https://github.com/TeamMoonstorm/Starstorm2/files/8897287/LogOutput-ExecutionerCamera.txt)
.

**Comment by Moffein** [comment]
For devs:
To fix this issue, in AxeSlam.cs, save the output cameraTargetParams.RequestAimType to a variable called aimRequest, then OnExit, instead of doing RequestAimType again, you should cameraTargetParams.RemoveRequest(aimRequest)

**Comment by Zenithrium** [comment]
would i get the output by just doing 
var aimRequest = CameraTargetParams.AimType.Aura; 
or 
var aimRequest = cameraTargetParams.RequestAimType(CameraTargetParams.AimType.Aura);
haven't dealt with these before

**Comment by Moffein** [comment]
2nd one.
RequestAimType returns the AimRequest object that is being used.
The reason the current code breaks is because it creates an AimRequest at the start and never actually removes it with RemoveRequest()

**Comment by Zenithrium** [comment]
Attempted to do the fix you said here: https://github.com/Zenithrium/Starstorm2/commit/1cb0f461224d3983ef705831b96f763f182d703c
but it doesn't seem to work? Doesn't throw any errors, but has the same issue it seems

**Comment by Moffein** [comment]
Only other guess would be to change it to AddParamsOverride/overrideRequest.Dispose(), since that's what Sniper/Railgunner use for their scope. Refer to Railgunner's BaseScopeState.

**Comment by Zenithrium** [comment]
Looking at the code and I'm not sure I'm following - the RG code in BaseScopeState does use cameraTargetParams.AddParamsOverride, and that could work, but I'm not sure how to translate CameraTargetParams.AimType.Aura to something that works in cameraParamsData. It also seems like overrideRequest.Dispose() is only used for the crosshair, and the camera is dealt with via cameraTargetParams.RemoveParamsOverride() instead. From all I can see it just appears that the two parameters of cameraTargetParams.AddParamsOverride are unhelpfully assigned as "cameraParamsData = this.cameraParams.data" and "priority = this.cameraOverridePriority" which are not given values, at least in any place I could find. Sorry if I'm missing something.
