### ISSUE TITLE
Commando Helot/Hornet/Stealth Skin Bug - Minor

### ISSUE THREAD

**Issue by BloodyGH** [TeamMoonstorm/Starstorm2#603]
Selecting the Stealth skin for Commando after first selecting the Helot/Hornet skin inherits the Stealth colour scheme but superimposed over the former skin. This does not translate into the run itself however and occurs only in character select. Upon starting the run the correct skin and colour scheme are present.

Replication:
>Start game
> Single / Multiplayer
> Select Commando
> Select Hornet/Helot skin
> Select Stealth skin

**Comment by swuff-star** [comment]
closing this bc its technically a vanilla bug. [kingenderbrine's lobbyskinsfix](https://thunderstore.io/package/KingEnderBrine/LobbySkinsFix/) fixes. couldve sworn we had this as a dependency but maybe not?
