### ISSUE TITLE
Diary Not Granting Levels

### ISSUE THREAD

**Issue by Slipskip** [TeamMoonstorm/Starstorm2#605]
As of the latest MSU 2.2.0 update Diary no longer granted levels on stage entry. Downgrading to MSU 2.1.0 removes the issue.

Log provided but there's zero error or anything as of line 979 where I gave myself diary then changed stage.
[LogOutput.log](https://github.com/user-attachments/files/17288783/LogOutput.log)

**Comment by Nebby1999** [comment]
Issue was upstream on MSU, fixed with version 2.2.1 of the API
