### ISSUE TITLE
Remuneration Not Granting Items

### ISSUE THREAD

**Issue by Slipskip** [TeamMoonstorm/Starstorm2#607]
Much like Diary Remuneration isn't spawning the item interactable on stage entry with the latest MSU 2.2 Update but does correctly on MSU 2.1. Very likely the same root problem as Diary and fixing one will most likely fix both.

Log attached but nothing obvious in there from what I can see.
[LogOutput.log](https://github.com/user-attachments/files/17293776/LogOutput.log)

**Comment by Nebby1999** [comment]
Issue was upstream on MSU, fixed with version 2.2.1 of the API
