### ISSUE TITLE
[Chirr] Mastery skin missing? 

### ISSUE THREAD

**Issue by SirWinchesterII** [TeamMoonstorm/Starstorm2#608]
You fixed the nems but not my girl chirr? :( 

Same issue as the nemesis' and executioner mastery skins that existed in a previous recent version, where the mastery skins were seemingly missing as an option, Chirr seems to have been skipped.

I know the skin exists, I can see it in the logbook, please fix this! Chirr is my absolute favourite and I'd love to see what unique model you devs might have come up with!

![Logbook challenge](https://github.com/user-attachments/assets/9caa544d-6df8-443d-ba2d-65d7c18f82ee)
![missing skin](https://github.com/user-attachments/assets/f9b03e7a-fd95-472b-9da6-3872c340c3ff)

**Comment by Slipskip** [comment]
While the achievement has been in the game since Chirrs release as a form of future proofing the skin itself has never actually been in a build of ss2 as it's still in production.

**Comment by yarrowyeen** [comment]
![image](https://github.com/user-attachments/assets/ac29541a-0e3b-4d8d-8af6-ac747f895992)
she never had a mastery.....
