### ISSUE TITLE
Greater Warbanner does not disappear and could break the game

### ISSUE THREAD

**Issue by Lin-Ain** [TeamMoonstorm/Starstorm2#63]
When placing a new Gbanner, the old Gbanner would not disappear. And it once broke the FPS of my game when I entered Gilded Coast with an equipment drone equipped with Gbanner. The equipment drone equipped with Gbanner spawned a large amount of Gbanner rapidly. When it found any target, at least 30 Gbanner were spawned within 1 or 2 second. Quickly, the map Gilded Coast was covered by hundreds of Gbanner and the visual range spheres created by them. **_My FPS dropped from 90 to 10_** after one minute passed even with the lowest graphic settings. This situation did not appear in common environment stages. In common stages, the equipment drone still spawned new Gbanners without deleting old ones continuously, but it would not spawned a large amount of Gbanners frequently. I forgot to keep the log file so you need to test it by yourselves. I thought **_it is a serious bug_** as it can break the game, and I hoped you can fix it with high priority.

The buff provided by Gbanner was not correctly implemented as well. I could not feel the differences while standing inside the range.

**Comment by Zenithrium** [comment]
greater warbanner, coders bane

**Comment by leMalfaisant** [comment]
minor correction, greater warbanner buff does mostly work, the regen and crit work and i think you just didn't seem to notice it however cooldown reduction is broken right now.
