### ISSUE TITLE
Stuck on 49% 

### ISSUE THREAD

**Issue by EldinDC** [TeamMoonstorm/Starstorm2#636]
Was playing fine yesterday with my friend, but today the game was stuck on 76%
we tried messing with files and configs and even did the whole verify files and fresh profile and my test profile is stuck on 49%.

Best i can guess is that executioner has a bug with the game.

The test profile has Bepinex, API and Starstorm 2 with its dependencies

[LogOutput.log](https://github.com/user-attachments/files/17623680/LogOutput.log)

**Comment by Hevia** [comment]
new update broke the game. Wait for us to release a fix
