### ISSUE TITLE
Game stuck on loadding

### ISSUE THREAD

**Issue by ENDER-Jake** [TeamMoonstorm/Starstorm2#656]
it always stuck when this log appear
[Error  : Unity Log] InvalidOperationException: Parameter count of hook for Void TeleportBody(RoR2.CharacterBody, UnityEngine.Vector3) doesn't match, must be 2
Stack trace:
MonoMod.RuntimeDetour.Hook..ctor (System.Reflection.MethodBase from, System.Reflection.MethodInfo to, System.Object target, MonoMod.RuntimeDetour.HookConfig& config) (at <4e2760c7517c4ea79c633d67e84b319f>:IL_018A)
MonoMod.RuntimeDetour.Hook..ctor (System.Reflection.MethodBase from, System.Reflection.MethodInfo to, System.Object target, MonoMod.RuntimeDetour.HookConfig config) (at <4e2760c7517c4ea79c633d67e84b319f>:IL_0000)
MonoMod.RuntimeDetour.Hook..ctor (System.Reflection.MethodBase from, System.Reflection.MethodInfo to, System.Object target) (at <4e2760c7517c4ea79c633d67e84b319f>:IL_001D)
MonoMod.RuntimeDetour.Hook..ctor (System.Reflection.MethodBase method, System.Delegate to) (at <4e2760c7517c4ea79c633d67e84b319f>:IL_000E)
MonoMod.RuntimeDetour.HookGen.HookEndpoint._NewHook (System.Reflection.MethodBase from, System.Delegate to) (at <4e2760c7517c4ea79c633d67e84b319f>:IL_0000)
MonoMod.RuntimeDetour.HookGen.HookEndpoint._Add[TDelegate] (System.Func`3[T1,T2,TResult] gen, TDelegate hookDelegate) (at <4e2760c7517c4ea79c633d67e84b319f>:IL_003C)
MonoMod.RuntimeDetour.HookGen.HookEndpoint.Add (System.Delegate hookDelegate) (at <4e2760c7517c4ea79c633d67e84b319f>:IL_0000)
MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Add (System.Reflection.MethodBase method, System.Delegate hookDelegate) (at <4e2760c7517c4ea79c633d67e84b319f>:IL_0028)
MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Add[T] (System.Reflection.MethodBase method, System.Delegate hookDelegate) (at <4e2760c7517c4ea79c633d67e84b319f>:IL_0000)
On.RoR2.TeleportHelper.add_TeleportBody (On.RoR2.TeleportHelper+hook_TeleportBody ) (at <31f65161844847298d505f59815204b4>:IL_000A)
SS2.Survivors.Executioner2.Hook () (at C:/Users/color/Desktop/code/Starstorm2/SS2-Project/Assets/Starstorm2/Modules/Characters/Survivors/Executioner2.cs:141)
SS2.Survivors.Executioner2.Initialize () (at C:/Users/color/Desktop/code/Starstorm2/SS2-Project/Assets/Starstorm2/Modules/Characters/Survivors/Executioner2.cs:62)
MSU.CharacterModule.InitializeCharacters (BepInEx.BaseUnityPlugin plugin, System.Collections.Generic.List`1[T] bodies, MSU.IContentPieceProvider`1[T] provider) (at D:/RoR2Related/Projects/MSUDev/Packages/teammoonstorm-moonstormsharedutils/Runtime/Code/Modules/CharacterModule.cs:144)
MSU.CharacterModule+<InitializeCharactersFromProvider>d__14.MoveNext () (at D:/RoR2Related/Projects/MSUDev/Packages/teammoonstorm-moonstormsharedutils/Runtime/Code/Modules/CharacterModule.cs:133)
MSU.CharacterModule+<InitializeCharacters>d__12.MoveNext () (at D:/RoR2Related/Projects/MSUDev/Packages/teammoonstorm-moonstormsharedutils/Runtime/Code/Modules/CharacterModule.cs:83)
SS2.SS2Content+<LoadStaticContentAsync>d__12.MoveNext () (at C:/Users/color/Desktop/code/Starstorm2/SS2-Project/Assets/Starstorm2/SS2Content.cs:44)
HG.Coroutines.ParallelProgressCoroutine+<InternalCoroutine>d__13.MoveNext () (at <50c819d11e6e4629a088087b9de5727d>:IL_007F)
HG.Coroutines.ParallelProgressCoroutine.MoveNext () (at <50c819d11e6e4629a088087b9de5727d>:IL_0000)
RoR2.RoR2Application+<LoadGameContent>d__112.MoveNext () (at <a149dbd7438a4e73b97d6600b3a2bbd4>:IL_013C)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <a20b3695b7ce4017b7981f9d06962bd1>:IL_0026)

**Comment by Hevia** [comment]
Yeah your game is not updated. The error is pointing to a new parameter that was added in the last update that youre missing but SS2 has
