### ISSUE TITLE
Nkhota's Heritage makes you unable to pickup items if unlocked

### ISSUE THREAD

**Issue by Phreelosu** [TeamMoonstorm/Starstorm2#7]
[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/8897389/LogOutput.log)

I unlocked all unlockables via CheatUnlocks cuz I'm lazy and testing

**Comment by Slipskip** [comment]
Adding to this: It doesn't matter if the items unlocked or not, Items still can't be picked up. Tested with command on and shrines, interactables and even command essence works but once you've selected the item from command you can't pick it up.
Adding my log as well just in case.
[LogOutput-ItemPickupsBroken.txt](https://github.com/TeamMoonstorm/Starstorm2/files/8897593/LogOutput-ItemPickupsBroken.txt)

**Comment by Nebby1999** [comment]
Closing issue as the issue was a lack of a proper FPTS installation
