### ISSUE TITLE
Wierd particle bug with gen loop as nemesis commando

### ISSUE THREAD

**Issue by Kickem404** [TeamMoonstorm/Starstorm2#74]
![image](https://user-images.githubusercontent.com/115917239/196022509-e28eec9d-7fd4-47ee-b250-c144e5c70527.png)
happens when using decisive strike with gen loop

**Comment by Kickem404** [comment]
should note, goes away when you have the loop go off, other than that it just flashes

**Comment by Kickem404** [comment]
it also starts flashing faster as it goes on? it has to be something with the loop

**Comment by Zenithrium** [comment]
My guess is it's related to the fact that nemmando's model is scaled improperly - (see: the end of stage teleporter vfx is huge). I believe this'll take a bit of effort if it is that, and probably even more if it isn't! so uh, I'll leave this one for now. thanks for the report & hopefully we'll get to it soon

**Comment by HelveticaLizard** [comment]
I also had this happen after picking up Gen Loop

Youtube Video Showing Bug:
https://youtu.be/Rk3aR2i3qPU

Modlist:
bbepis-BepInExPack-5.4.2103
RiskofThunder-HookGenPatcher-1.2.3
tristanmcpherson-R2API-4.4.1
TheRealElysium-EmptyChestsBeGone-1.1.1
XoXFaby-BetterUI-2.6.1
KingEnderBrine-ProperSave-2.8.9
Rune580-Risk_Of_Options-2.5.3
Bubbet-ZioConfigFile-1.0.1
Bubbet-ZioRiskOfOptions-1.0.0
Bubbet-RiskUI-1.4.0
JohnEdwa-RTAutoSprintEx-2.1.2
MagnusMagnuson-ScannerPlusOne-2.7.0
MagnusMagnuson-ItemExchangeNotifier-1.4.1
XoXFaby-BetterGameplay-1.1.2
PseudoCoffee-RemoveScreenEffectsTintsAndDistortions-1.0.3
6thmoon-HistoryFix-0.4.0
Quizzik-AddFoVSettings-1.0.0
TheTimesweeper-SillyItems-1.2.2
NetherCrowCSOLYOO-BazaarExpand-2.0.2
KingEnderBrine-ScrollableLobbyUI-1.7.6
KingEnderBrine-ExtraSkillSlots-1.5.1
Xan-HPBarAPI-2.0.0
VarnaScelestus-Ephemeral_Coins-2.3.3
PicklePower01-MuteEquipment-1.0.0
TeamMoonstorm-MoonstormSharedUtils-1.0.1
TeamMoonstorm-Starstorm2-0.3.43

**Comment by leMalfaisant** [comment]
fixed by #144
