### ISSUE TITLE
Cant pick up items

### ISSUE THREAD

**Issue by Max91425** [TeamMoonstorm/Starstorm2#75]
after the release i immediently decided to play and as soon as i enter the second Stage i couldnt pick up any items whatsoever
i have no idea if its actually a bug related to this mod or because i happened to had a few other mods installed well here i go i guess
[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/9793797/LogOutput.log)

**Comment by leMalfaisant** [comment]
aerolt issue, thanks for filing a report tho
