### ISSUE TITLE
The gold gained from M.I.D.A.S should scale.

### ISSUE THREAD

**Issue by efhunter** [TeamMoonstorm/Starstorm2#77]
The phrasing on the description suggests this is not intended behavior.

"Sacrifice 50% of your current health, gaining the same amount of health lost as gold."

With a Safer Spaces active, you do not lose any health, but still gain the gold from the health you would have lost without it.

Not related to the issue, but on the topic of the equipment's balance:
-------------

I'd suggest increasing the cooldown, as 30 seconds is quite short for a portable, infinite blood shrine. Safer Spaces aside, getting any kind of healing trivializes the downside, and allows you to print money, which creates a snowball effect since taking damage becomes even less of a problem for you with all the extra items you're getting. If not the cooldown, perhaps the amount of gold received should be adjusted.

Another thing to consider is that this equipment becomes objectively worse in multiplayer (the more players, the more expensive chests are). The equipment has less output despite the same input. It would be nice if the gold received scaled with player amount.

**Comment by Zenithrium** [comment]
I mean it is sort of like a portable blood shrine, and they don't hurt you if you have safer spaces - it's just a very strong synergy. I suppose it could increase the cooldown or slightly adjust the income - just have to find a good balance. 

I do think some player scaling would be a good idea.

**Comment by leMalfaisant** [comment]
M.I.D.A.S giving gold through Safer Spaces is intentional. It isn't very useful past the earlygame where you aren't really going to be having that insane of healing so I think it's fine. We'll think about increasing the cooldown, and I agree, it should scale in MP.

**Comment by Zenithrium** [comment]
Closing, but still considering a cooldown increase.
