### ISSUE TITLE
Nemmando Skin defaulting when going to Bazaar

### ISSUE THREAD

**Issue by Mohl97** [TeamMoonstorm/Starstorm2#78]
It's pretty much as it says. I had to upload the start of the log separately from the error I believe is causing it, as the log file's 55mb worth of a console-spamming error I'm about to report separately.
[Log Start.txt](https://github.com/TeamMoonstorm/Starstorm2/files/9793873/Log.Start.txt)

`[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
RoR2.CharacterModel+ParentedPrefabDisplay.Apply (
RoR2.CharacterModel characterModel, UnityEngine.GameObject prefab, UnityEngine.Transform parent, UnityEngine.Vector3 localPosition, UnityEngine.Quaternion localRotation, UnityEngine.Vector3 localScale) (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0000)
RoR2.CharacterModel.InstantiateDisplayRuleGroup (RoR2.DisplayRuleGroup displayRuleGroup, RoR2.ItemIndex itemIndex, RoR2.EquipmentIndex equipmentIndex) (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0099)
DMD<EnableItemDisplay>?-1768936192._RoR2_CharacterModel::EnableItemDisplay (RoR2.CharacterModel this, RoR2.ItemIndex itemIndex) (at <5017dbc8aa3c420b8ef77828fcbdd6ae>:IL_0035)
DMD<>?-1768936192.Trampoline<RoR2.CharacterModel::EnableItemDisplay>?-1609265152 (RoR2.CharacterModel , RoR2.ItemIndex ) (at <8e94021d52fd44b4a34229fdd2f7be07>:IL_0020)
HandPlugin.Hooks.FixBearDisplay+<>c.<.ctor>b__0_0 (On.RoR2.CharacterModel+orig_EnableItemDisplay orig, RoR2.CharacterModel self, RoR2.ItemIndex itemIndex) (at <30a5180db4f94709b3e448db96b8f5bb>:IL_0026)
DMD<>?-1768936192.Hook<RoR2.CharacterModel::EnableItemDisplay>?80158336 (RoR2.CharacterModel , RoR2.ItemIndex ) (at <60e7c4bdc94b4c8bbfbb63f55b4d0a48>:IL_0014)
RoR2.CharacterModel.UpdateItemDisplay (RoR2.Inventory inventory) (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0014)
RoR2.CharacterModel.OnInventoryChanged () (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0021)
DMD<OnInventoryChanged>?-1768936192._RoR2_CharacterBody::OnInventoryChanged (RoR2.CharacterBody this) (at <50e3e05eb5b244c5a2af73b66c700d99>:IL_028F)
DMD<>?-1768936192.Trampoline<RoR2.CharacterBody::OnInventoryChanged>?-819499008 (RoR2.CharacterBody ) (at <2ebbb31c8a1c4a1ba39658b6171d506a>:IL_0020)
AncientScepter.AncientScepterItem.On_CBOnInventoryChanged (On.RoR2.CharacterBody+orig_OnInventoryChanged orig, RoR2.CharacterBody self) (at <f40b9abdc8e243bd98696a7e01d381e5>:IL_0001)
DMD<>?-1768936192.Hook<RoR2.CharacterBody::OnInventoryChanged>?-764792064 (RoR2.CharacterBody ) (at <5eecb2060d544759a1a55d6fdd406fac>:IL_0014)
RoR2.CharacterBody.get_masterObject () (at <abee4f3b46184662b4d0bd0bc9965114>:IL_00DF)
RoR2.CharacterBody.get_master () (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0000)
Moonstorm.Starstorm2.SS2ExperienceManager+<>c.<CharacterBody_RecalculateStats>b__9_0 (RoR2.CharacterBody body) (at <4ae128aba0154b99b4b2b6a06b42e576>:IL_0000)
MonoMod.Cil.RuntimeILReferenceBag+FastDelegateInvokers.Invoke[T1] (T1 arg1, MonoMod.Cil.RuntimeILReferenceBag+FastDelegateInvokers+Action`1[T1] del) (at <6733e342b5b549bba815373898724469>:IL_0000)
RoR2.CharacterBody.RecalculateStats () (at <abee4f3b46184662b4d0bd0bc9965114>:IL_000B)
DMD<>?-1768936192.Trampoline<RoR2.CharacterBody::RecalculateStats>?-1462593536 (RoR2.CharacterBody ) (at <11cc30629b7e46938497a442b8489ca4>:IL_0020)
NS_KingKombatArena.KingKombatArenaMainPlugin.CharacterBody_RecalculateStats_Hook (On.RoR2.CharacterBody+orig_RecalculateStats orig, RoR2.CharacterBody self) (at <c29712ffcf51444f8a9c310b91a04382>:IL_0000)
DMD<>?-1768936192.Hook<RoR2.CharacterBody::RecalculateStats>?962482560 (RoR2.CharacterBody ) (at <c2f33eb484f94f25a3c3b810747c8ab9>:IL_0014)
DMD<>?-1768936192.Trampoline<RoR2.CharacterBody::RecalculateStats>?505608192 (RoR2.CharacterBody ) (at <58e6566d3fbe49df8121f3ef5a316389>:IL_0020)
ChefMod.ChefPlugin+<>c.<registerBuff>b__45_0 (On.RoR2.CharacterBody+orig_RecalculateStats orig, RoR2.CharacterBody self) (at <2d7b1507595048f48c0d2036423da8b8>:IL_0001)
DMD<>?-1768936192.Hook<RoR2.CharacterBody::RecalculateStats>?-507620992 (RoR2.CharacterBody ) (at <b5321749eaa0415bbba127f933f2cf34>:IL_0014)
DMD<>?-1768936192.Trampoline<RoR2.CharacterBody::RecalculateStats>?-1420962816 (RoR2.CharacterBody ) (at <f1700cec51564e4ea1b2feb5cb8d5d8a>:IL_0020)
EnforcerPlugin.EnforcerModPlugin.CharacterBody_RecalculateStats (On.RoR2.CharacterBody+orig_RecalculateStats orig, RoR2.CharacterBody self) (at <69654e2f0ed14f72bae60268f865a1db>:IL_0001)
DMD<>?-1768936192.Hook<RoR2.CharacterBody::RecalculateStats>?-1484828288 (RoR2.CharacterBody ) (at <13f9ab36385840d2a551163508b1ee43>:IL_0014)
DMD<>?-1768936192.Trampoline<RoR2.CharacterBody::RecalculateStats>?-1514559488 (RoR2.CharacterBody ) (at <1b6f46495fad4060bfaaf8b5226da2c5>:IL_0020)
PaladinMod.PaladinPlugin.CharacterBody_RecalculateStats (On.RoR2.CharacterBody+orig_RecalculateStats orig, RoR2.CharacterBody self) (at <b775a35ec89d410aa7f5dc707436c37f>:IL_0001)
DMD<>?-1768936192.Hook<RoR2.CharacterBody::RecalculateStats>?-1122334208 (RoR2.CharacterBody ) (at <2fdd0a37ac2044248b74ba66101f8e4d>:IL_0014)
DMD<>?-1768936192.Trampoline<RoR2.CharacterBody::RecalculateStats>?1688232960 (RoR2.CharacterBody ) (at <7a699d4455354508a8b373b2e5917af2>:IL_0020)
Moonstorm.ContentManagerSystem.OnRecaluclateStats (On.RoR2.CharacterBody+orig_RecalculateStats orig, RoR2.CharacterBody self) (at <063d682f64ed4bf497da1a430a6c6b6c>:IL_0012)
DMD<>?-1768936192.Hook<RoR2.CharacterBody::RecalculateStats>?2048938368 (RoR2.CharacterBody ) (at <2dd87b2542a949da932c6bf2a2e40b32>:IL_000A)
DMD<>?-1768936192.Trampoline<RoR2.CharacterBody::RecalculateStats>?2134719488 (RoR2.CharacterBody ) (at <47b8e42d7f3f4ef69af43af109ba4465>:IL_0020)
NS_KingModUtilities.BonusStatHandler.RecalculateStats_Hook (On.RoR2.CharacterBody+orig_RecalculateStats orig, RoR2.CharacterBody self) (at <ba74344591b24172bcda190869e5814d>:IL_002E)
DMD<>?-1768936192.Hook<RoR2.CharacterBody::RecalculateStats>?-737126784 (RoR2.CharacterBody ) (at <c6892f93e6aa455ea4ab528a2fce5c2e>:IL_0014)
DMD<Start>?-1768936192._RoR2_CharacterBody::Start (RoR2.CharacterBody this) (at <e9f08bcda0ec4fa3ac10f74957bb38b6>:IL_0052)
DMD<>?-1768936192.Trampoline<RoR2.CharacterBody::Start>?-128673792 (RoR2.CharacterBody ) (at <452c59fc7830441da703903770c2c66f>:IL_0020)
NS_KingKombatArena.KingKombatArenaMainPlugin.CharacterBody_Start_Hook (On.RoR2.CharacterBody+orig_Start orig, RoR2.CharacterBody self) (at <c29712ffcf51444f8a9c310b91a04382>:IL_0000)
DMD<>?-1768936192.Hook<RoR2.CharacterBody::Start>?-1532978944 (RoR2.CharacterBody ) (at <fa9a2afd1f684e4fba377f553d7b37f0>:IL_0014)
`

**Comment by leMalfaisant** [comment]
Do you remember/know what items were in your inventory at the time?

**Comment by Mohl97** [comment]
![image](https://user-images.githubusercontent.com/13591160/196025364-e9e31e7c-2a17-4ae8-bbb8-bb90b9f9ef3c.png)
Only items I picked up since going in there were the two void items, relic of force, and leeching seed.

**Comment by prodzpod** [comment]
please provide a full list of mods you are using.

**Comment by Nebby1999** [comment]
Closing this as it's stale, and also because 0.4 completely redid nemmando.

Reopen if needed
