### ISSUE TITLE
Console spam caused by missing file/assembly.

### ISSUE THREAD

**Issue by Mohl97** [TeamMoonstorm/Starstorm2#79]
as referenced in #78 , my console is getting spammed by the following: 

`[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'UnityEngine.Networking, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
`
This otherwise uses the same bits of log as in that issue. I'll have to finish up my current run, restart, and get a cleaner, full log in a bit.

Edit: Here's the log: 
[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/9793997/LogOutput.log)

**Comment by leMalfaisant** [comment]
Has this happened since 3.40 released?

**Comment by prodzpod** [comment]
Does not seem to be a SS2 issue. first, integrity check your RoR2 instance through steam or epic and disable cache from r2modman 

Settings -> Toggle download cache (disable it)
Settings -> Export profile as code
Settings -> Change profile
Import -> From code
Select new profile
Start modded
Toggle the download cache (enable it)

if problems persist, make a new issue.
