### ISSUE TITLE
Nkota's Heritage onCharacterLevelUp NRE spam

### ISSUE THREAD

**Issue by Phreelosu** [TeamMoonstorm/Starstorm2#80]
[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/9794046/LogOutput.log)

seems to be related to character levelup, the item itself works, but the NRE appears even without the item in player inventory
incredibly heavy on performance, the NRE spam I mean

**Comment by Zenithrium** [comment]
My guess is that the code is assuming the party leveling up has an inventory before actually checking to see if it does. Hopefully should be fixed in the next patch.

**Comment by Zenithrium** [comment]
Should be fixed in 0.3.40. Hopefully.
