### ISSUE TITLE
Nemmando's animations gets stuck when he gets frozen during his special.

### ISSUE THREAD

**Issue by FORCED-REASSEMBLY** [TeamMoonstorm/Starstorm2#81]
[NemmandoSpecialFreeze.txt](https://github.com/TeamMoonstorm/Starstorm2/files/9794109/NemmandoSpecialFreeze.txt)

**Comment by Zenithrium** [comment]
Will get fixed in upcoming patch. Thanks for the report!

**Comment by Zenithrium** [comment]
Fixed in 0.3.40!
