### ISSUE TITLE
Nemmando has big scepter and also judgement cut (Alt R + Scepter) doesn't give more hits with higher attack speed also no more red filter when doing the attack

### ISSUE THREAD

**Issue by GGBE123** [TeamMoonstorm/Starstorm2#82]
- Big Scepter display
- Scepter slash ( judgment cut) not scaling with attack speed + no more funny red and black filter when using the attack

**Comment by leMalfaisant** [comment]
Scepter fix is waiting for the Scepter mod to update, red and black filter is intentionally gone. Will take a look on if it scales with attack speed.

**Comment by Zenithrium** [comment]
So interestingly, nowhere in the code does it ever attempt to implement some kind of attack speed scaling. I think the skill's already pretty strong so I think we'll just remove it from the description.

**Comment by GGBE123** [comment]
> So interestingly, nowhere in the code does it ever attempt to implement some kind of attack speed scaling. I think the skill's already pretty strong so I think we'll just remove it from the description.

Wait what? Out of all the neat things I remember from Starstorm 2, one of the big ones was nemmando having his alt r scaling with attack if you had scepter it scaled soo good to the point that if you had too much attack speed he wouldn't move until every hit is dealt like his default R. Please reconsider, his alt R by default not scaling with attack speed was remedied by having a scepter version that did. To my knowledge, up to the newest version of Starstorm 2 released ( not nightly) he still had this feature. Sorry if I sound a little rude, I'm just kinda upset that the solution was to remove it entirely. I know that making things do more with attack speed is not of high priority, but it's a fun thing that can make the character feel way better.

**Comment by Zenithrium** [comment]
That's fair - I just kind of wanted consistency across the character. Maybe I'll make attack speed be about half as effective on Decisive and normally effective on Judgement. I'm worried it could make the ability too strong but I guess I'm up for testing it.

**Comment by Zenithrium** [comment]
Big scepter display should be fixed on scepter mod's end soon, hopefully. I think the cut-to-red screen was a bit much for something you can do every 10 or so seconds, but maybe not
