### ISSUE TITLE
Nemmando's scepter ability gets removed when using the "next_stage" command. Randomly duing the run his skin gets changed to the default one.

### ISSUE THREAD

**Issue by FORCED-REASSEMBLY** [TeamMoonstorm/Starstorm2#83]
[NemmandoScepterRemoved.txt](https://github.com/TeamMoonstorm/Starstorm2/files/9794596/NemmandoScepterRemoved.txt)

**Comment by FORCED-REASSEMBLY** [comment]
+ some of his item displays get removed and you get the scepter ability back when you use your equipment

**Comment by leMalfaisant** [comment]
Has this issue popped up since?

**Comment by leMalfaisant** [comment]
haven't had any reports of this since/was never able to replicate this so i'm closing
