### ISSUE TITLE
Picking up Pogo Stick seems to break multiple animations, leaving items and bodies around after they die. Happened on Executioner, no clue yet about any other survivors.

### ISSUE THREAD

**Issue by oceanselemon** [TeamMoonstorm/Starstorm2#84]
[Debug  :Starstorm 2 Nightly] aghhhhhh: 12 :: Line: 54, Method OnInventoryChanged 
^This would pop up in console multiple times^
[ss2error.txt](https://github.com/TeamMoonstorm/Starstorm2/files/9795375/ss2error.txt)

![20221016125327_1](https://user-images.githubusercontent.com/108032917/196051225-907d72f0-2339-4faf-8c7d-8225658fd4f7.jpg)

Here is an console log and screenshot from the run. It only got worse after the screenshot until it suddenly crashed. I believe the yellow streaks were either wisp projectiles or executioner's primary.

**Comment by oceanselemon** [comment]
Wait, just realized that pogo stick wasnt't ss2. Still might be the cause, but probably not.

**Comment by oceanselemon** [comment]
Now I frankly have no idea, as it is still happening, and that error is not showing up. Please remove this bug report, as I don't know how.

**Comment by Zenithrium** [comment]
haha oh that debug message is from nkotas unlock i totally missed that part of this issue
