### ISSUE TITLE
When using the "GoldenCoastPlus" Mod, the item "Guardians Eye" Appears as a massive ball on the screen.

### ISSUE THREAD

**Issue by Ryguy1412** [TeamMoonstorm/Starstorm2#85]
![image](https://user-images.githubusercontent.com/115951819/196055410-8f06497c-c91e-4a01-8a1b-237956d61a9a.png)

**Comment by Zenithrium** [comment]
This is an issue caused by default IDRs - nemmando's model is weirdly scaled, thus making the default size too large.

**Comment by Zenithrium** [comment]
to clarify - if GoldenCoastPlus has a github, this should be posted there I believe

**Comment by leMalfaisant** [comment]
Unfortunately, this is out of our hands. I'll close this issue. You should probably speak to the creator of GoldenCoastPlus about this though.
