### ISSUE TITLE
Storms do not show in multiplayer

### ISSUE THREAD

**Issue by Mick0604** [TeamMoonstorm/Starstorm2#86]
When a storm or event happens the second player cannot see them on the screen

**Comment by Mick0604** [comment]
this also applies for visual only storms, the second player and on cannot see them at all

**Comment by Kickem404** [comment]
they also don't see the text letting them know its happening, atleast thats what i heard from my friends

**Comment by Mick0604** [comment]
> 

Yea my friends also told me they couldnt see blizzards or ash storms

**Comment by Zenithrium** [comment]
do either of you still have this log / have a new log where the same thing happens? we need a log from both of you so we can get the client and the host's end

**Comment by Kickem404** [comment]
sadly not no.

**Comment by Mick0604** [comment]
Yea i could do that

**Comment by Zenithrium** [comment]
should be fixed in 0.3.48
