### ISSUE TITLE
Prototype Jet Boots proc on player while using artifact of chaos

### ISSUE THREAD

**Issue by Mick0604** [TeamMoonstorm/Starstorm2#87]
while using artifact of chaos jet boots hurt the player and can insta kill with certain items

**Comment by Zenithrium** [comment]
wow that's hilarious that that hasn't been noticed by now. thanks for the report, this should be in the patch today

**Comment by Mick0604** [comment]
> wow that's hilarious that that hasn't been noticed by now. thanks for the report, this should be in the patch today

yea i was playing artifact of chaos as a joke and jumped and lost seers proced and i died instantly

**Comment by Zenithrium** [comment]
that's incredible

**Comment by Zenithrium** [comment]
Fixed in 0.3.40!
