### ISSUE TITLE
X-4 Stimulant Text Issue

### ISSUE THREAD

**Issue by drp527** [TeamMoonstorm/Starstorm2#88]
X-4 Stimulant stats display weirdly. The secondary cooldown reduction reads as "{0} (+{0} per stack)" and the healing reads as "{3} plus {1}% ({2}% per stack)". All other items from the mod display correctly.
![image](https://user-images.githubusercontent.com/2908082/196071312-7823c3ad-e2f2-4887-bd61-7ce2d4dfa276.png)
[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/9796241/LogOutput.log)

**Comment by Zenithrium** [comment]
Yep, should be fixed in today's patch. Thanks for the report!

**Comment by Zenithrium** [comment]
Fixed in 0.3.40!
