### ISSUE TITLE
Minuano skin makes Nemmando disappear 

### ISSUE THREAD

**Issue by FORCED-REASSEMBLY** [TeamMoonstorm/Starstorm2#9]
Selecting the skin makes nemmando disappear, leaving only the sword and gun. I have yet to unlock the GM and find out if that causes the same issue

**Comment by Nebby1999** [comment]
Fixed in the newest alpha release of SS2.

Link (Requires access to the SS2 discord server): https://discordapp.com/channels/753709254598328400/754484105584050216/993600660199198881
