### ISSUE TITLE
Nemmando is in constant genesis loop animation

### ISSUE THREAD

**Issue by NoxThePreacher** [TeamMoonstorm/Starstorm2#90]
Have a couple of other mods installed, didn't test on a clean starstorm 2 yet

P.S. Ignore the background audio

https://user-images.githubusercontent.com/115974896/196108387-7e76a4ab-8efa-43e0-a64a-dda88ecf9536.mp4

**Comment by Nebby1999** [comment]
This cannot be fixed, due to the fact that Nemmando's Armature is scaled by a factor of 100, most VFX such as Vagrant's electricity and Teleporter particles are scaled to the armature's scaling.

This will be fixed whenever a new nemmando model is made
