### ISSUE TITLE
Security drones spawn void infestor

### ISSUE THREAD

**Issue by NoNamedTerror** [TeamMoonstorm/Starstorm2#91]
Im playing ss2 for the first time so i dont know the exact name of the item but the one that spawns the security drones after killing an elite spawns a void infestor after they die which kind of makes it difficult to clear out void seeds since they get to another enemy, void touch them, when they die another void drone spawns whicj just continues the cycle. Dunno if this is intentional

**Comment by swuff-star** [comment]
LMFAO 
silly oversight woops
