### ISSUE TITLE
EXTREME LIGHT (Executioner bug)

### ISSUE THREAD

**Issue by Spongie101** [TeamMoonstorm/Starstorm2#96]
Not sure what exactly caused it. Just paused the game and when I un-paused this happened. Only mod installed is SS2.
![image_2022-10-17_114017708](https://user-images.githubusercontent.com/116029377/196256688-33901f4f-36b7-40fd-9827-51daccc50065.png)

**Comment by Nebby1999** [comment]
log

**Comment by Spongie101** [comment]
Ok I think it's caused by pausing the game with Hunter's Sigil active, because pausing while in movement doesn't cause the bug. But uh, I'll try and get that to you when I actually finish the run. (Bug doesn't persist between stages)
