### ISSUE TITLE
X-4 First Stack Issue

### ISSUE THREAD

**Issue by drp527** [TeamMoonstorm/Starstorm2#98]
I'm honestly not sure if this is only a tooltip mismatch or if there's something actually happening, but the visible cooldown for the secondary skill when hovering in-game doesn't change with the first stack of the item. Each extra copy after that correctly reduces the cooldown by .25 seconds, but the first seems to do nothing beyond the healing effect.
[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/9804842/LogOutput.log)
![Risk_of_Rain_2_PFfdQ5Swdk](https://user-images.githubusercontent.com/2908082/196291883-b9bbe3da-c117-4487-b749-4ec6ff787b2a.png)
![Risk_of_Rain_2_v80hSpXwfu](https://user-images.githubusercontent.com/2908082/196291892-d41018ef-bc83-4dd3-a2dd-6da851935af0.png)

**Comment by Zenithrium** [comment]
hm. I'm pretty sure it should work - what mod is displaying the tooltips?

**Comment by drp527** [comment]
BetterUI is the mod giving the tooltip info.

**Comment by drp527** [comment]
Ok, yeah, went back in and tried to do some further looking. You're right, as far as I can tell this is actually working as intended and the tooltip is just wrong (at 8 stacks the cooldown indicator on the skill itself is 3 and counting it out more or less matches that) so it's down to however BetterUI is pulling that data.

**Comment by Zenithrium** [comment]
I think visually on the skills it might seem like it's doing nothing as the game rounds up, say 5 -> 4.75 back up to 5. I'll definitely look into it though

**Comment by Zenithrium** [comment]
So it doesn't seem like the first stack isn't working on my end, but my build has a couple changes so I'll only mark this as "fixed in next release."
