### ISSUE TITLE
Skateboard lets nemmando run in all directions but doesn't buff him 

### ISSUE THREAD

**Issue by Kickem404** [TeamMoonstorm/Starstorm2#99]
happened during a run with a friend, although i wasn't hosting so that could have an aspect to do with it

**Comment by leMalfaisant** [comment]
Log?

**Comment by Kickem404** [comment]
don't have it anymore sadly.

**Comment by Zenithrium** [comment]
Think we know the issue - was this in multiplayer and you weren't the host?
